import { test, expect } from '@playwright/test';
import fs from 'node:fs/promises';

test('Continuous bay count updates framing, unequal lengths, drawings and saved inputs', async ({ page }) => {
  test.setTimeout(90000);
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await expect(page.getByText('Live calculation', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Number of bays')).toHaveCount(0);
  await page.getByLabel('Span arrangement').selectOption('continuous');
  const count = page.getByLabel('Number of bays'), host = page.locator('.viewer-canvas');
  await expect(count).toHaveValue('1'); await expect(count.locator('option')).toHaveCount(6);
  await count.selectOption('3');
  await expect(page.getByLabel('Bay 3 length', { exact: true })).toHaveValue('300');
  await page.getByLabel('Bay 2 length', { exact: true }).fill('240');
  await expect(page.locator('.bay-summary')).toContainText('4 support lines');
  await expect(page.locator('.bay-summary')).toContainText('840 in');
  await page.getByRole('button', { name: '3D viewer', exact: true }).click();
  await expect(host).toHaveAttribute('data-bay-count', '3');
  await expect(host).toHaveAttribute('data-model-length', '21336');
  await expect(host).toHaveAttribute('data-reference-supports', '4');
  await expect(host).toHaveAttribute('data-building-columns', '8');
  await expect(host).toHaveAttribute('data-moment-frames', '4');
  await expect(host).toHaveAttribute('data-girder-members', '1');
  await expect(page.getByLabel('Inspect 3D connection').locator('optgroup').filter({ hasText: 'S4 · Primary frame knee' })).toHaveCount(1);
  await expect(page.getByText('Live calculation', { exact: true })).toBeVisible({ timeout: 30000 });
  await fs.mkdir('tmp/viewer', { recursive: true });
  await page.getByRole('button', { name: 'Dismiss notification', exact: true }).click();
  await page.screenshot({ path: 'tmp/viewer/continuous-three-bays.png', fullPage: true });
  await page.getByRole('button', { name: 'Crane loads', exact: true }).click();
  await expect(page.getByLabel('Travel origin end', { exact: true })).toHaveValue('840');
  await page.getByRole('button', { name: 'Geometry', exact: true }).click();
  await page.getByRole('button', { name: 'SI', exact: true }).click();
  await expect(page.getByLabel('Bay 2 length', { exact: true })).toHaveValue('6096');
  await page.reload();
  await expect(count).toHaveValue('3');
  await expect(page.getByLabel('Bay 2 length', { exact: true })).toHaveValue('6096');
  await expect(page.getByText('Live calculation', { exact: true })).toBeVisible({ timeout: 30000 });
  await page.getByRole('button', { name: 'Diagrams', exact: true }).click();
  await expect(page.locator('svg.cad-sheet')).toContainText('S4');
  await expect(page.locator('svg.cad-sheet')).toContainText('21,336 mm');
  await page.getByRole('button', { name: '3D viewer', exact: true }).click();
  await page.getByLabel('Span arrangement').selectOption('simple');
  await expect(count).toHaveCount(0); await expect(host).toHaveAttribute('data-girder-members', '3');
  await page.getByLabel('Span arrangement').selectOption('continuous'); await expect(count).toHaveValue('3');
  await page.getByLabel('Bolts & connections', { exact: true }).uncheck();
  await count.selectOption('6');
  await expect(host).toHaveAttribute('data-reference-supports', '7');
  await expect(host).toHaveAttribute('data-building-columns', '14');
  await expect(host).toHaveAttribute('data-moment-frames', '7');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Whole structure', exact: true }).click();
  await page.locator('.viewer').screenshot({ path: 'tmp/viewer/continuous-six-bays-mobile.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await count.selectOption('1');
  await expect(page.getByLabel('Bay 2 length', { exact: true })).toHaveCount(0);
  await expect(host).toHaveAttribute('data-building-columns', '4');
  await expect(host).toHaveAttribute('data-girder-members', '1');
  await expect(page.locator('.live-state')).toHaveText('Live calculation', { timeout: 30000 });
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('cranecalc.project.v1')!));
  expect(saved.spans).toEqual([7620]); expect(saved.cranes[0].travelEnd).toBe(7620);
  expect(errors).toEqual([]);
});

test('Bay removal trims custom crane travel while preserving valid ranges', async ({ page }) => {
  await page.goto('/'); await page.getByLabel('Span arrangement').selectOption('continuous');
  await page.getByLabel('Number of bays').selectOption('3');
  await page.getByRole('button', { name: 'Crane loads', exact: true }).click();
  await page.getByLabel('Travel origin start', { exact: true }).fill('350');
  await page.getByLabel('Travel origin end', { exact: true }).fill('800');
  await page.getByRole('button', { name: 'Geometry', exact: true }).click();
  await page.getByLabel('Number of bays').selectOption('1');
  await page.getByRole('button', { name: 'Crane loads', exact: true }).click();
  await expect(page.getByLabel('Travel origin start', { exact: true })).toHaveValue('0');
  await expect(page.getByLabel('Travel origin end', { exact: true })).toHaveValue('300');
  await page.getByLabel('Travel origin end', { exact: true }).fill('250');
  await page.getByRole('button', { name: 'Geometry', exact: true }).click();
  await page.getByLabel('Number of bays').selectOption('2');
  await page.getByRole('button', { name: 'Crane loads', exact: true }).click();
  await expect(page.getByLabel('Travel origin end', { exact: true })).toHaveValue('250');
  await expect(page.getByText('Live calculation', { exact: true })).toBeVisible({ timeout: 30000 });
});
