import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import { exampleProject } from '../../src/engine/defaults';
import { fingerprint } from '../../src/engine/calculate';
test('live checks, source gate, validated PDF and immutable SVG downloads',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.getByText('Live calculation',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Generate output',exact:true})).toBeDisabled();
 await expect(page.locator('.results-panel')).toHaveCSS('opacity','1');await page.screenshot({path:'tmp/pdfs/workspace-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Equations & checks',exact:true}).click();
 await page.getByRole('button',{name:/Vertical crane-load deflection/}).click();await expect(page.locator('.katex-display').first()).toBeVisible();
 await page.getByRole('button',{name:'Criteria',exact:true}).click();
 await page.getByLabel('Report scope').selectOption('analysis');
 await expect(page.getByRole('button',{name:'Generate output',exact:true})).toBeEnabled();
 const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Generate output',exact:true}).click();const download=await downloadEvent;
 await fs.mkdir('tmp/pdfs',{recursive:true});await download.saveAs('tmp/pdfs/validated-analysis.pdf');
 await expect(page.getByRole('dialog',{name:'Generated output'})).toBeVisible();
 const cadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Download CAD linework (.dxf)',exact:true}).click();const cad=await cadEvent;await cad.saveAs('tmp/pdfs/runway-linework.dxf');const cadContent=await fs.readFile('tmp/pdfs/runway-linework.dxf','utf8');expect(cadContent).toContain('$INSUNITS\n70\n1\n');expect(cadContent).toContain('DIMENSION');
 const svgEvent=page.waitForEvent('download');await page.getByRole('button',{name:'runway elevation',exact:true}).click();const svg=await svgEvent;await svg.saveAs('tmp/pdfs/runway-elevation.svg');expect(await fs.readFile('tmp/pdfs/runway-elevation.svg','utf8')).toContain('<svg');
 await page.getByRole('button',{name:'Close output'}).click();
 await page.getByRole('button',{name:'Project',exact:true}).click();await page.getByLabel('Project title').fill('Changed project revision');
 await expect(page.getByText('Live calculation',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Generated output',exact:true}).click();await expect(page.getByText(/Previous revision; current inputs have changed/)).toBeVisible();
 const previousCadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Download CAD linework (.dxf)',exact:true}).click();const previousCad=await previousCadEvent;expect(await fs.readFile((await previousCad.path())!,'utf8')).toBe(cadContent);
 expect(errors).toEqual([]);
 const p=structuredClone(exampleProject);const response=await request.post('/api/report',{data:{input:p,revision:fingerprint(p)}});expect(response.status()).toBe(422);
 p.scope='analysis';const stale=await request.post('/api/report',{data:{input:p,revision:'stale'}});expect(stale.status()).toBe(409);
 p.section.Ix*=1.1;const tampered=await request.post('/api/report',{data:{input:p,revision:fingerprint(p)}});expect(tampered.status()).toBe(422);expect((await tampered.json()).errors.join(' ')).toContain('selected AISC');
});
test('CAD sketches switch views, print monochrome, zoom, update dimensions and fit mobile',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.getByText('Live calculation',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Diagrams',exact:true}).click();
 const viewer=page.getByRole('region',{name:'2D engineering sketch viewer'}),canvas=viewer.locator('.drafting-canvas');
 await expect(canvas).toHaveAttribute('data-drawing','runway-elevation');await expect(canvas).toHaveClass(/model-space/);
 await expect(viewer.locator('svg.cad-sheet')).toHaveAccessibleName(/Runway elevation/);
 await page.screenshot({path:'tmp/pdfs/cad-elevation-desktop.png',fullPage:true});
 await viewer.getByRole('button',{name:'Plan',exact:true}).click();await expect(canvas).toHaveAttribute('data-drawing','runway-plan');
 await viewer.getByRole('button',{name:'Section',exact:true}).click();await expect(canvas).toHaveAttribute('data-drawing','girder-section');
 await expect(viewer.locator('svg.cad-sheet')).toContainText('d = 24.1 in');await expect(viewer.locator('svg.cad-sheet text').filter({hasText:'NOT FOR FABRICATION'})).toHaveCSS('font-size','8px');
 await viewer.getByRole('button',{name:'Paper drawing view'}).click();await expect(canvas).toHaveClass(/paper-space/);
 await expect(viewer.locator('polygon[data-layer="OUTLINE"]').first()).toHaveCSS('fill','none');
 await page.screenshot({path:'tmp/pdfs/cad-section-paper.png',fullPage:true});
 await viewer.getByRole('button',{name:'Zoom in sketch'}).click();await expect(canvas).toHaveAttribute('data-zoom','1.25');
 await viewer.getByRole('button',{name:'Fit sketch'}).click();await expect(canvas).toHaveAttribute('data-zoom','1');
 await page.getByLabel('Section type').selectOption('welded');await page.getByLabel('Depth, d',{exact:true}).fill('30');await expect(viewer.locator('svg.cad-sheet')).toContainText('d = 30 in');
 await page.getByRole('button',{name:'SI',exact:true}).click();await expect(viewer.locator('svg.cad-sheet')).toContainText('d = 762 mm');
 await viewer.getByRole('button',{name:'CAD drawing view'}).click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'tmp/pdfs/cad-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
 await expect(page.getByRole('button',{name:'Generate output',exact:true})).toBeDisabled();expect(errors).toEqual([]);
});
test('invalid edits block export; units preserve engineering inputs; mobile layout fits',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Criteria',exact:true}).click();await page.getByLabel('Report scope').selectOption('analysis');await expect(page.getByRole('button',{name:'Generate output',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Geometry',exact:true}).click();await page.getByLabel('Section type').selectOption('welded');await page.getByLabel('Depth, d',{exact:true}).fill('0');await expect(page.getByText('Correct inputs to continue')).toBeVisible();await expect(page.getByRole('button',{name:'Generate output',exact:true})).toBeDisabled();
 await page.getByLabel('Depth, d',{exact:true}).fill('24');await expect(page.getByRole('button',{name:'Generate output',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'SI',exact:true}).click();await expect(page.getByLabel('Depth, d',{exact:true})).toHaveValue('609.6');
 await expect(page.getByRole('button',{name:'Generate output',exact:true})).toBeEnabled();await expect(page.locator('.results-panel')).toHaveCSS('opacity','1');await page.setViewportSize({width:390,height:844});await page.screenshot({path:'tmp/pdfs/workspace-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
});
test('3D viewer renders, changes camera and wireframe, tracks inputs, and fits mobile',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.getByText('Live calculation',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Generate output',exact:true})).toBeDisabled();
 const canvas=page.getByLabel('Interactive 3D runway model');await expect(canvas).toBeVisible();
 await expect(page.locator('.viewer-canvas')).toHaveAttribute('data-wheel-count','2');
 await expect(page.locator('.results-panel')).toHaveCSS('opacity','1');
 await fs.mkdir('tmp/pdfs',{recursive:true});await page.screenshot({path:'tmp/pdfs/compact-3d-desktop.png',fullPage:true});
 const initialView=await canvas.screenshot();
 await page.getByRole('button',{name:'End',exact:true}).click();expect(await canvas.screenshot()).not.toEqual(initialView);await expect(page.locator('.viewer-canvas')).toHaveAttribute('data-camera-view','End');
 await page.getByRole('button',{name:'Top',exact:true}).click();await expect(page.locator('.viewer-canvas')).toHaveAttribute('data-camera-view','Top');
 const solidView=await canvas.screenshot();
 await page.getByLabel('Wireframe',{exact:true}).check();expect(await canvas.screenshot()).not.toEqual(solidView);await expect(page.getByLabel('Wireframe',{exact:true})).toBeChecked();
 await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.getByRole('button',{name:'Reset 3D view',exact:true}).click();
 await expect(page.locator('.viewer-canvas')).toHaveAttribute('data-camera-view','Isometric');
 await page.getByLabel('3D governing load case').selectOption('deflection');await expect(page.locator('.viewer-options>span')).not.toHaveText('Calculating…');
 await page.getByLabel('Section type').selectOption('welded');await page.getByLabel('Depth, d',{exact:true}).fill('20');await expect(page.getByText('Live calculation',{exact:true})).toBeVisible();await expect(page.locator('.viewer-canvas')).toHaveAttribute('data-model-depth','508');
 await page.getByRole('button',{name:'2D',exact:true}).click();await expect(canvas).toHaveCount(0);await expect(page.getByRole('img',{name:/Runway elevation/})).toBeVisible();
 await page.getByRole('button',{name:'3D viewer',exact:true}).click();await expect(canvas).toBeVisible();await expect(page.locator('.viewer')).toHaveClass(/expanded/);
 await page.getByLabel('Wireframe',{exact:true}).uncheck();
 await page.screenshot({path:'tmp/pdfs/3d-expanded.png',fullPage:true});
 await page.setViewportSize({width:875,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(875);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'tmp/pdfs/compact-3d-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
 expect(errors).toEqual([]);
});
test('3D graphics failure has a usable 2D fallback without changing export validation',async({page})=>{
 await page.addInitScript({content:`const originalContext=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type==='webgl2')return null;return originalContext.call(this,type,...args);};`});
 await page.goto('/');await expect(page.getByText('WebGL 2 is unavailable. Use the 2D elevation view.')).toBeVisible();
 await page.getByRole('button',{name:'2D',exact:true}).click();await expect(page.getByRole('img',{name:/Runway elevation/})).toBeVisible();
 await expect(page.getByRole('button',{name:'Generate output',exact:true})).toBeDisabled();
});
test('AISC reference support framing renders, changes shapes and height, and preserves engineering inputs',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.getByText('Live calculation',{exact:true})).toBeVisible();
 const host=page.locator('.viewer-canvas'),canvas=page.getByLabel('Interactive 3D runway model');
 await expect(host).toHaveAttribute('data-reference-supports','2');await expect(host).toHaveAttribute('data-reference-column','W14X90');await expect(host).toHaveAttribute('data-reference-crosshead','W12X40');
 const before=await page.evaluate(()=>localStorage.getItem('cranecalc.project.v1'));
 await page.locator('.viewer-framing summary').click();
 await expect(page.getByLabel('Reference framing',{exact:true})).toBeChecked();
 await page.getByLabel('Reference frame type').selectOption('rolled');await expect(host).toHaveAttribute('data-frame-style','rolled');
 await page.getByLabel('Reference column shape').selectOption('W12X65');await expect(host).toHaveAttribute('data-reference-column','W12X65');
 await page.getByLabel('Reference bracket shape').selectOption('W16X50');await expect(host).toHaveAttribute('data-reference-crosshead','W16X50');
 await page.getByLabel('Reference column height').selectOption('6096');await expect(host).toHaveAttribute('data-reference-height','6096');
 const framed=await canvas.screenshot();
 await page.getByLabel('Reference framing',{exact:true}).uncheck();await expect(host).toHaveAttribute('data-reference-supports','0');expect(await canvas.screenshot()).not.toEqual(framed);
 await page.getByLabel('Reference framing',{exact:true}).check();
 expect(await page.evaluate(()=>localStorage.getItem('cranecalc.project.v1'))).toBe(before);
 await expect(page.getByRole('button',{name:'Generate output',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'3D viewer',exact:true}).click();await expect(host).toHaveAttribute('data-reference-height','6096');await expect(host).toHaveAttribute('data-reference-column','W12X65');
 await page.screenshot({path:'tmp/pdfs/reference-framing-isometric.png',fullPage:true});
 for(const view of ['Front','End','Top']){await page.getByRole('button',{name:view,exact:true}).click();await page.screenshot({path:`tmp/pdfs/reference-framing-${view.toLowerCase()}.png`,fullPage:true});}
 await page.getByRole('button',{name:'Reset 3D view'}).click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'tmp/pdfs/reference-framing-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
 await page.locator('.viewer-framing summary').click();await page.getByLabel('Shape labels',{exact:true}).uncheck();await page.getByLabel('Wireframe',{exact:true}).check();
 expect(errors).toEqual([]);
});
test('Bolt-level 3D connections support close-ups, part selection, toggling and persistence',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.getByText('Live calculation',{exact:true})).toBeVisible();
 const before=await page.evaluate(()=>localStorage.getItem('cranecalc.project.v1'));
 await page.getByRole('button',{name:'3D viewer',exact:true}).click();
 const host=page.locator('.viewer-canvas'),canvas=page.getByLabel('Interactive 3D runway model');
 await expect(host).toHaveAttribute('data-detail-level','bolts');await expect(host).toHaveAttribute('data-fastener-count','220');
 const whole=await canvas.screenshot();await page.getByLabel('Inspect 3D connection').selectOption('seat-1');
 await expect(host).toHaveAttribute('data-inspection-focus','seat-1');expect(await canvas.screenshot()).not.toEqual(whole);
 await page.getByLabel('Inspect 3D part').selectOption('S2-GS-1');const selected=page.getByRole('status',{name:'Selected 3D part'});
 await expect(selected).toContainText('Girder seat bolt');await expect(selected).toContainText('0.75 in');await expect(selected).toContainText('two washers');
 await page.getByRole('button',{name:'Clear selected part'}).click();await expect(selected).toHaveCount(0);
 await page.getByLabel('Inspect 3D connection').selectOption('base-0');await page.getByLabel('Inspect 3D part').selectOption('S1-AR-1');
 await expect(selected).toContainText('Base anchor rod');await expect(selected).toContainText('1 in');
 await page.getByRole('button',{name:'Top',exact:true}).click();await page.getByRole('button',{name:'Clear selected part'}).click();
 const size=await canvas.boundingBox();await canvas.click({position:{x:size!.width*.375,y:size!.height*.317}});await expect(selected).toContainText('Base anchor rod');
 const assembly=await canvas.screenshot();await page.getByRole('button',{name:'Zoom to selected 3D part'}).click();expect(await canvas.screenshot()).not.toEqual(assembly);
 await page.getByRole('button',{name:'Isometric',exact:true}).click();
 await fs.mkdir('tmp/viewer',{recursive:true});await page.locator('.viewer').screenshot({path:'tmp/viewer/verified-base-anchor.png'});
 await page.getByLabel('Inspect 3D connection').selectOption('rail');await page.getByLabel('Inspect 3D part').selectOption('RC-7-R');await expect(selected).toContainText('Rail clip bolt');
 await page.locator('.viewer').screenshot({path:'tmp/viewer/verified-rail-clip.png'});
 await page.getByLabel('Bolts & connections',{exact:true}).uncheck();await expect(host).toHaveAttribute('data-detail-level','members');await expect(host).toHaveAttribute('data-fastener-count','0');await expect(host).toHaveAttribute('data-inspection-focus','');await expect(selected).toHaveCount(0);
 await page.reload();await expect(page.getByLabel('Bolts & connections',{exact:true})).not.toBeChecked();
 await page.getByLabel('Bolts & connections',{exact:true}).check();await expect(host).toHaveAttribute('data-fastener-count','220');
 expect(await page.evaluate(()=>localStorage.getItem('cranecalc.project.v1'))).toBe(before);
 await page.getByRole('button',{name:'3D viewer',exact:true}).click();await page.getByLabel('Inspect 3D connection').selectOption('seat-0');
 for(const view of ['Front','End','Top','Isometric'])await page.getByRole('button',{name:view,exact:true}).click();
 await page.getByLabel('Wireframe',{exact:true}).check();await page.getByLabel('Wireframe',{exact:true}).uncheck();
 await page.setViewportSize({width:390,height:844});await page.getByLabel('Inspect 3D connection').selectOption('base-1');await page.getByLabel('Inspect 3D part').selectOption('S2-AR-1');
 await page.locator('.viewer').screenshot({path:'tmp/viewer/verified-bolt-mobile.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
 await page.getByRole('button',{name:'Reset 3D view'}).click();await expect(host).toHaveAttribute('data-inspection-focus','');
 await expect(page.getByRole('button',{name:'Generate output',exact:true})).toBeDisabled();expect(errors).toEqual([]);
});
test('Fastener detail exposes heads, nuts, washers and helical threads in assembled and exploded views',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.getByText('Live calculation',{exact:true})).toBeVisible();
 const before=await page.evaluate(()=>localStorage.getItem('cranecalc.project.v1'));
 await page.getByRole('button',{name:'3D viewer',exact:true}).click();
 const open=page.getByRole('button',{name:'Fastener detail',exact:true}),dialog=page.getByRole('dialog',{name:'Fastener detail'}),host=dialog.locator('.fastener-canvas'),canvas=dialog.getByLabel('Interactive fastener assembly');
 await expect(open).toBeEnabled();await open.click();await expect(dialog).toBeVisible();await expect(host).toHaveAttribute('data-thread-kind','helical');await expect(host).toHaveAttribute('data-assembly-mode','exploded');
 for(const component of ['Hex bolt head','Head washer','Bolt shank','Nut washer','Hex nut','Helical thread'])await expect(dialog.getByText(component,{exact:true})).toBeVisible();
 await fs.mkdir('tmp/viewer',{recursive:true});await dialog.screenshot({path:'tmp/viewer/fastener-exploded.png'});
 const exploded=await canvas.screenshot();await dialog.getByRole('button',{name:'Assembled',exact:true}).click();await expect(host).toHaveAttribute('data-assembly-mode','assembled');expect(await canvas.screenshot()).not.toEqual(exploded);
 await dialog.getByRole('button',{name:'Nut & threads',exact:true}).click();await dialog.screenshot({path:'tmp/viewer/fastener-threads.png'});
 await dialog.getByRole('button',{name:'Head',exact:true}).click();await dialog.getByRole('button',{name:'Side',exact:true}).click();await dialog.screenshot({path:'tmp/viewer/fastener-assembled.png'});
 await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(open).toBeFocused();
 await page.getByLabel('Inspect 3D connection').selectOption('seat-0');await page.getByLabel('Inspect 3D part').selectOption('S1-EB-1');await open.click();await expect(host).toHaveAttribute('data-fastener-id','S1-EB-1');await expect(host).toHaveAttribute('data-fastener-anchor','false');await dialog.getByRole('button',{name:'Close fastener detail'}).click();
 await page.getByLabel('Inspect 3D connection').selectOption('base-0');await open.click();await expect(host).toHaveAttribute('data-fastener-anchor','true');await page.keyboard.press('Escape');
 await page.getByLabel('Inspect 3D part').selectOption('S1-AR-1');await open.click();await expect(host).toHaveAttribute('data-fastener-anchor','true');
 await expect(dialog.getByText('Anchor rod',{exact:true})).toBeVisible();await expect(dialog.getByText('Washer',{exact:true})).toBeVisible();await expect(dialog.getByText('Hex nut',{exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'Head',exact:true})).toHaveCount(0);
 await dialog.screenshot({path:'tmp/viewer/fastener-anchor.png'});await dialog.getByRole('button',{name:'Assembled',exact:true}).click();await page.keyboard.press('Escape');
 await page.getByLabel('Inspect 3D connection').selectOption('far-seat-0');await page.getByLabel('Inspect 3D part').selectOption('F-S1-EB-1');await open.click();await expect(host).toHaveAttribute('data-fastener-id','F-S1-EB-1');
 await page.setViewportSize({width:390,height:844});await expect(canvas).toBeVisible();await dialog.screenshot({path:'tmp/viewer/fastener-mobile.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.keyboard.press('Escape');
 expect(await page.evaluate(()=>localStorage.getItem('cranecalc.project.v1'))).toBe(before);
 await page.getByLabel('Bolts & connections',{exact:true}).uncheck();await expect(open).toBeDisabled();expect(errors).toEqual([]);
});
test('Whole reference structure shows both runways, building framing and persistent bay settings',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{if(!localStorage.getItem('cranecalc.viewer.reference.v1'))localStorage.setItem('cranecalc.viewer.reference.v1',JSON.stringify({shown:true,labels:false,column:'W14X90',crosshead:'W12X40',height:3048}));});
 await page.goto('/');await expect(page.getByText('Live calculation',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'3D viewer',exact:true}).click();const host=page.locator('.viewer-canvas');
 await expect(host).toHaveAttribute('data-reference-runways','2');await expect(host).toHaveAttribute('data-building-columns','4');await expect(host).toHaveAttribute('data-reference-bay-width','9144');await expect(host).toHaveAttribute('data-inspection-focus','');
 const before=await page.evaluate(()=>localStorage.getItem('cranecalc.project.v1'));
 await expect(host).toHaveAttribute('data-runway-support-type','column-brackets');
 await page.getByLabel('Inspect 3D connection').selectOption('seat-0');await page.getByLabel('Inspect 3D part').selectOption('S1-EB-1');await expect(page.getByRole('status',{name:'Selected 3D part'})).toContainText('Bracket end plate to building-column inner flange');
 await fs.mkdir('tmp/viewer',{recursive:true});await page.locator('.viewer').screenshot({path:'tmp/viewer/column-bracket-closeup.png'});
 await page.getByLabel('Inspect 3D connection').selectOption('far-seat-0');await page.getByLabel('Inspect 3D part').selectOption('F-S1-EB-1');await expect(page.getByRole('status',{name:'Selected 3D part'})).toContainText('Column bracket bolt');await page.getByRole('button',{name:'Zoom to selected 3D part'}).click();
 await page.getByRole('button',{name:'Whole structure',exact:true}).click();
 await page.getByLabel('Inspect 3D connection').selectOption('far-base-1');await page.getByLabel('Inspect 3D part').selectOption('F-S2-AR-1');await expect(page.getByRole('status',{name:'Selected 3D part'})).toContainText('Opposite runway reference');
 await page.getByRole('button',{name:'Zoom to selected 3D part'}).click();await page.getByRole('button',{name:'Whole structure',exact:true}).click();await expect(host).toHaveAttribute('data-inspection-focus','');await expect(page.getByRole('status',{name:'Selected 3D part'})).toHaveCount(0);
 await page.locator('.viewer-framing summary').click();await expect(page.getByLabel('Whole structure',{exact:true})).toBeChecked();
 await page.getByLabel('Whole structure',{exact:true}).uncheck();await expect(host).toHaveAttribute('data-reference-runways','1');await expect(host).toHaveAttribute('data-building-columns','2');await expect(host).toHaveAttribute('data-fastener-count','70');
 await page.getByRole('button',{name:'Whole structure',exact:true}).click();await expect(host).toHaveAttribute('data-reference-runways','2');await expect(host).toHaveAttribute('data-fastener-count','220');
 await page.getByLabel('Reference bay width').selectOption('12192');await page.getByLabel('Reference roof clearance').selectOption('3048');await expect(host).toHaveAttribute('data-reference-bay-width','12192');
 expect(await page.evaluate(()=>localStorage.getItem('cranecalc.project.v1'))).toBe(before);
 await fs.mkdir('tmp/viewer',{recursive:true});for(const view of ['Isometric','End','Top','Front']){await page.getByRole('button',{name:view,exact:true}).click();await page.locator('.viewer').screenshot({path:`tmp/viewer/whole-verified-${view.toLowerCase()}.png`});}
 await page.reload();await page.getByRole('button',{name:'3D viewer',exact:true}).click();await expect(host).toHaveAttribute('data-reference-runways','2');await expect(host).toHaveAttribute('data-reference-bay-width','12192');
 await page.locator('.viewer-framing summary').click();await expect(page.getByLabel('Reference roof clearance')).toHaveValue('3048');await page.getByRole('button',{name:'SI',exact:true}).click();await expect(page.getByLabel('Reference bay width')).toHaveValue('12192');
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Whole structure',exact:true}).click();await page.locator('.viewer').screenshot({path:'tmp/viewer/whole-verified-mobile.png'});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await expect(page.getByRole('button',{name:'Generate output',exact:true})).toBeDisabled();expect(errors).toEqual([]);
});
test('Prefab moment frames expose bolt holes, knee and ridge connections and preserve project inputs',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.getByText('Live calculation',{exact:true})).toBeVisible();await page.getByRole('button',{name:'3D viewer',exact:true}).click();
 const host=page.locator('.viewer-canvas'),canvas=page.getByLabel('Interactive 3D runway model'),before=await page.evaluate(()=>localStorage.getItem('cranecalc.project.v1'));
 await expect(host).toHaveAttribute('data-frame-style','tapered');await expect(host).toHaveAttribute('data-building-columns','4');await expect(host).toHaveAttribute('data-fastener-count','220');
 await fs.mkdir('tmp/viewer',{recursive:true});await page.locator('.viewer').screenshot({path:'tmp/viewer/prefab-isometric.png'});
 await page.getByRole('button',{name:'End',exact:true}).click();await page.locator('.viewer').screenshot({path:'tmp/viewer/prefab-end-frame.png'});
 await page.getByLabel('Inspect 3D connection').selectOption('seat-0');await page.getByRole('button',{name:'Isometric',exact:true}).click();const installed=await canvas.screenshot();
 await page.getByLabel('Show bolt holes',{exact:true}).check();await expect(host).toHaveAttribute('data-hole-view','true');expect(await canvas.screenshot()).not.toEqual(installed);
 expect(Number(await host.getAttribute('data-hole-count'))).toBeGreaterThan(300);await expect(page.locator('.viewer-inspect')).toContainText('plate holes · Fasteners hidden');
 await expect(page.getByLabel('Inspect 3D part').locator('option').filter({hasText:'Seat mounting bolt'})).toHaveCount(0);await page.locator('.viewer').screenshot({path:'tmp/viewer/exposed-seat-holes.png'});
 await page.getByLabel('Inspect 3D connection').selectOption('knee-0-0');await expect(page.getByLabel('Inspect 3D part')).toContainText('Moment-frame knee end plate');await page.getByRole('button',{name:'Front',exact:true}).click();await page.locator('.viewer').screenshot({path:'tmp/viewer/exposed-knee-holes.png'});
 await page.getByLabel('Show bolt holes',{exact:true}).uncheck();await page.getByLabel('Inspect 3D part').selectOption('B1-S1-KB-1');await expect(page.getByRole('status',{name:'Selected 3D part'})).toContainText('Moment-frame knee bolt');
 await page.getByRole('button',{name:'Fastener detail',exact:true}).click();await expect(page.locator('.fastener-canvas')).toHaveAttribute('data-fastener-id','B1-S1-KB-1');await page.keyboard.press('Escape');
 await page.getByLabel('Inspect 3D connection').selectOption('knee-1-0');await page.getByLabel('Inspect 3D part').selectOption('B2-S1-KB-1');await expect(page.getByRole('status',{name:'Selected 3D part'})).toContainText('Moment-frame knee bolt');
 await page.getByLabel('Inspect 3D connection').selectOption('ridge-0');await page.getByLabel('Show bolt holes',{exact:true}).check();await expect(page.getByLabel('Inspect 3D part')).toContainText('Ridge moment-splice plate');await page.locator('.viewer').screenshot({path:'tmp/viewer/exposed-ridge-holes.png'});
 await page.getByLabel('Show bolt holes',{exact:true}).uncheck();await page.getByRole('button',{name:'Whole structure',exact:true}).click();await page.locator('.viewer-framing summary').click();
 await page.getByLabel('Reference roof pitch').selectOption('4');await expect(host).toHaveAttribute('data-roof-slope','4');await page.reload();await expect(page.getByText('Live calculation',{exact:true})).toBeVisible();await page.getByRole('button',{name:'3D viewer',exact:true}).click();await expect(host).toHaveAttribute('data-roof-slope','4');await expect(host).toHaveAttribute('data-frame-style','tapered');
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'End',exact:true}).click();await page.locator('.viewer').screenshot({path:'tmp/viewer/prefab-mobile.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
 expect(await page.evaluate(()=>localStorage.getItem('cranecalc.project.v1'))).toBe(before);await page.getByLabel('Bolts & connections',{exact:true}).uncheck();await expect(page.getByLabel('Show bolt holes',{exact:true})).toBeDisabled();await expect(host).toHaveAttribute('data-hole-view','false');expect(errors).toEqual([]);
});
test('AISC rolled-section picker loads exact properties, updates views and survives units and reload',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.getByText('Live calculation',{exact:true})).toBeVisible();
 const shape=page.getByLabel('AISC girder section'),depth=page.getByLabel('Depth, d',{exact:true});
 await expect(page.getByLabel('Section type')).toHaveValue('rolled');await expect(shape).toHaveValue('W24X84');await expect(shape.locator('option')).toHaveCount(290);
 await expect(depth).toHaveValue('24.1');await expect(depth).toHaveAttribute('readonly','');
 await page.locator('.catalogue-properties summary').click();await expect(page.locator('.catalogue-properties')).toContainText('2,370 in⁴');await expect(page.locator('.catalogue-properties')).toContainText('12,800 in⁶');
 await shape.selectOption('W30X99');await expect(depth).toHaveValue('29.7');await expect(page.getByText('Live calculation',{exact:true})).toBeVisible();
 await expect(page.locator('.catalogue-properties')).toContainText('3,990 in⁴');await expect(page.locator('.viewer-canvas')).toHaveAttribute('data-model-depth','754.38');
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('cranecalc.project.v1')!));expect(saved.section.A).toBe(29*25.4**2);expect(saved.section.Ix).toBe(3990*25.4**4);expect(saved.section.Cw).toBe(26800*25.4**6);expect(saved.section.Fy).toBe(345);
 await page.getByRole('button',{name:'SI',exact:true}).click();await expect(depth).toHaveValue('754.38');
 await page.getByRole('button',{name:'Criteria',exact:true}).click();await page.getByLabel('Report scope').selectOption('analysis');await expect(page.getByRole('button',{name:'Generate output',exact:true})).toBeEnabled();
 await page.reload();await expect(page.getByText('Live calculation',{exact:true})).toBeVisible();await expect(shape).toHaveValue('W30X99');await expect(depth).toHaveValue('754.38');
 await page.getByRole('button',{name:'Diagrams',exact:true}).click();await page.getByRole('region',{name:'2D engineering sketch viewer'}).getByRole('button',{name:'Section',exact:true}).click();await expect(page.locator('svg.cad-sheet')).toContainText('d = 754.38 mm');
 await shape.selectOption('');await expect(depth).not.toHaveAttribute('readonly','');await expect(page.getByText('Correct inputs to continue')).toBeVisible();
 await page.getByLabel('Catalogue / property source').fill('User verified supplier properties');await expect(page.getByRole('button',{name:'Generate output',exact:true})).toBeEnabled();
 await page.setViewportSize({width:390,height:844});await shape.selectOption('W24X84');await page.locator('.catalogue-properties summary').click();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
 expect(errors).toEqual([]);
});
