import { describe,it,expect } from 'vitest';
import { Beam, beamSystem } from '../src/engine/beam';
import { calculate, fingerprint, validateProject } from '../src/engine/calculate';
import { exampleProject } from '../src/engine/defaults';
import { sectionProperties } from '../src/engine/section';
import { fromDisplay,toDisplay } from '../src/engine/units';
import { reportHtml } from '../server/report';
const project=()=>structuredClone(exampleProject);
describe('Independent beam benchmarks',()=>{
 it('matches simply supported central point load, including deflection',()=>{const L=6000,P=100000,EI=200000*3e8;const r=new Beam(0,L,EI,[0,L]).evaluate([{x:L/2,p:P}]);expect(r.reactions[0].r).toBeCloseTo(P/2,5);expect(Math.max(...r.moment)).toBeCloseTo(P*L/4,3);expect(Math.max(...r.displacement)).toBeCloseTo(P*L**3/(48*EI),7);expect(r.equilibriumError).toBeLessThan(1e-9);});
 it('matches an off-node eccentric point-load deflection and reactions',()=>{const L=6000,a=1234,b=L-a,P=90000,EI=6e13;const r=new Beam(0,L,EI,[0,L]).evaluate([{x:a,p:P}]);expect(r.reactions[0].r).toBeCloseTo(P*b/L,5);for(let i=0;i<r.x.length;i++){const x=r.x[i];const exact=x<=a?P*b*x/(6*L*EI)*(L*L-b*b-x*x):P*a*(L-x)/(6*L*EI)*(L*L-a*a-(L-x)**2);expect(r.displacement[i]).toBeCloseTo(exact,7);}});
 it('matches UDL deflection and bending moment',()=>{const L=7000,q=2,EI=8e13;const r=new Beam(0,L,EI,[0,L]).evaluate([],q);expect(Math.max(...r.moment)).toBeCloseTo(q*L*L/8,3);expect(Math.max(...r.displacement)).toBeCloseTo(5*q*L**4/(384*EI),7);});
 it('matches continuous equal two-span UDL support moment and reactions',()=>{const L=5000,q=3;const r=beamSystem([L,L],8e13,'continuous').evaluate([],q);const at=r.x.indexOf(L);expect(r.moment[at]).toBeCloseTo(-q*L*L/8,3);expect(r.reactions[1].r).toBeCloseTo(5*q*L/4,5);expect(r.displacement[at]).toBe(0);});
 it('simple spans release moment at their shared support',()=>{const r=beamSystem([5000,5000],8e13,'simple').evaluate([{x:3500,p:100000}]);const indexes=r.x.flatMap((x,i)=>x===5000?[i]:[]);indexes.forEach(i=>expect(Math.abs(r.moment[i])).toBeLessThan(.01));});
});
describe('Section properties, units and validation',()=>{
 it('integrates a symmetrical welded I-section independently',()=>{const s=project().section;s.kind='welded';delete s.catalogueId;s.d=500;s.bf=200;s.tf=20;s.tw=10;const v=sectionProperties(s);expect(v.A).toBe(12600);expect(v.Ix).toBeCloseTo(2*(200*20**3/12+4000*240**2)+10*460**3/12,4);expect(v.cy).toBe(250);expect(v.Sx).toBe(v.Ix/250);});
 it('preserves every unit quantity through conversion',()=>{for(const q of ['length','force','moment','stress','area','inertia','modulus','warping','lineLoad','ratio'] as const)expect(fromDisplay(toDisplay(123456.78,q,'US'),q,'US')).toBeCloseTo(123456.78,7);});
 it('rejects invalid geometry, unloaded loads and incomplete properties',()=>{const p=project();p.section.d=1;p.cranes[0].wheels[0].unloaded=1e9;expect(validateProject(p).length).toBeGreaterThan(1);p.section.kind='rolled';expect(validateProject(p).some(x=>x.includes('catalogue'))).toBe(true);});
 it('rejects imported NaN, negative forces and unknown schema versions',()=>{const p=project();p.section.Fy=NaN;expect(validateProject(p).length).toBeGreaterThan(0);expect(validateProject({...project(),schemaVersion:2}).length).toBeGreaterThan(0);});
});
describe('Moving-load analysis and report gates',()=>{
 it('blocks complete code design on source/model gaps',()=>{const s=calculate(project());expect(s.analysis).not.toBeNull();expect(s.eligible).toBe(false);expect(s.checks.some(c=>c.id==='load-basis'&&c.status==='incomplete')).toBe(true);expect(s.checks.filter(c=>c.group==='Analysis').every(c=>c.status==='pass')).toBe(true);expect(()=>reportHtml(s)).toThrow();});
 it('allows validated analysis reports with failed serviceability criteria',()=>{const p=project();p.scope='analysis';p.verticalLimit=1e6;const s=calculate(p);expect(s.eligible).toBe(true);expect(s.checks.find(c=>c.id==='vertical')?.status).toBe('fail');const html=reportHtml(s);expect(html).toContain('FAILED ENGINEERING CRITERIA');expect(html).toContain('SUPPLIED-LOAD ANALYSIS REPORT ONLY');expect(html).toContain(s.revision);});
 it('prevents impact double counting and uses static loads for serviceability',()=>{const p=project();p.scope='analysis';const a=calculate(p);p.cranes[0].includesImpact=true;p.cranes[0].wheels.forEach(w=>w.loaded*=1.25);const b=calculate(p);expect(a.analysis!.demand.moment).toBeCloseTo(b.analysis!.demand.moment,3);expect(a.analysis!.demand.deflection).toBeCloseTo(b.analysis!.demand.deflection,7);});
 it('excludes impact from crane serviceability',()=>{const p=project();const a=calculate(p);p.cranes[0].impact=.5;const b=calculate(p);expect(a.analysis!.demand.deflection).toBeCloseTo(b.analysis!.demand.deflection,6);expect(b.analysis!.demand.moment).toBeGreaterThan(a.analysis!.demand.moment);});
 it('rejects impossible crane separation rather than returning zero demand',()=>{const p=project();p.cranes.push({...structuredClone(p.cranes[0]),id:'second',minSeparation:999999});const s=calculate(p);expect(s.eligible).toBe(false);expect(s.errors[0]).toContain('No crane positions');});
 it('preserves supplied input and creates distinct revisions',()=>{const p=project(),before=JSON.stringify(p);calculate(p);expect(JSON.stringify(p)).toBe(before);const old=fingerprint(p);p.title='Changed';expect(fingerprint(p)).not.toBe(old);});
 it('escapes untrusted project text in reports and SVG',()=>{const p=project();p.scope='analysis';p.title='<script>alert(1)</script>';const s=calculate(p);expect(reportHtml(s)).not.toContain('<script>alert');expect(reportHtml(s)).toContain('&lt;script&gt;');});
});
describe('Advanced runway configurations',()=>{
 it('analyzes multiple continuous spans with lateral restraints and two independent cranes',()=>{const p=project();p.scope='analysis';p.system='continuous';p.spans=[7620,7620];p.lateralBraceSpacing=3810;p.cranes[0].travelEnd=15240;p.cranes.push({...structuredClone(p.cranes[0]),id:'crane-2',name:'Second crane'});const s=calculate(p);expect(s.errors).toEqual([]);expect(s.analysis!.cases).toBeGreaterThan(100);expect(s.analysis!.envelope.some(r=>r.momentMin<0)).toBe(true);expect(s.analysis!.equilibriumError).toBeLessThan(1e-7);expect(s.analysis!.meshConvergence).toBeLessThan(.01);for(const lc of Object.values(s.analysis!.demand.governing))expect(lc.positions[1]-lc.positions[0]).toBeGreaterThanOrEqual(p.cranes[0].wheels.at(-1)!.offset+p.cranes[0].minSeparation-1e-6);},15000);
 it('adds exact cap-channel area and preserves symmetry in minor-axis properties',()=>{const s=project().section;s.kind='welded';delete s.catalogueId;const base=sectionProperties(s);s.kind='cap';s.capWidth=320;s.capDepth=100;s.capTf=12;s.capTw=12;const cap=sectionProperties(s);expect(cap.A-base.A).toBe(320*12+2*12*88);expect(cap.cy).toBeGreaterThan(base.cy);expect(cap.Iy).toBeGreaterThan(base.Iy);expect(cap.Cw).toBe(0);});
 it('includes manufacturer wheel loads placed exactly on a shared simple support only once',()=>{const r=beamSystem([5000,5000],8e13,'simple').evaluate([{x:5000,p:100000}]);expect(r.reactions.reduce((sum,r)=>sum+r.r,0)).toBeCloseTo(100000,6);expect(r.reactions[1].r).toBeCloseTo(100000,6);expect(Math.max(...r.displacement.map(Math.abs))).toBe(0);});
});
