import {checkFigureHtml,checkFigureCss} from '../components/checkFigures';
import {existingBracketLabel} from '../engine/bracketProfiles';
import {usesExistingBracket,existingBracket} from '../engine/existingBracket';
import {flangeTieGeometry} from '../engine/tieGeometry';
import {connectionCoordination} from '../engine/connectionCoordination';
import {simpleSupportInput} from '../engine/simpleSupports';
import {sharedSupportRows} from '../components/simpleSupportSheet';
import {cappedMechanics} from '../engine/cappedMechanics';
import {girderStrength} from '../engine/aiscStrength';
import katex from 'katex';
import type { CalculationSnapshot,CheckResult } from '../engine/types';
import { format,formatSectionMass,type Quantity } from '../engine/units';
import { references } from '../engine/references';
import { drawingSvg,engineeringSketches } from '../components/drafting';
const e=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function compactReport(s:CalculationSnapshot,fonts:string,detailed=false){
 const p=s.input,d=p.details!,a=s.designAnalysis!,r=s.detailResults!,prop=s.properties!,demo=p.reportPurpose==='demonstration';
 const f=(v:number|undefined,q:Quantity='length')=>e(format(v,q,p.units,4));
 const math=(tex:string)=>katex.renderToString(tex,{throwOnError:false,displayMode:true});
 const table=(headers:string[],rows:(string|number)[][],cls='')=>`<table class="${cls}"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 const numeric=(checks:CheckResult[])=>checks.length?table(['Check','Demand','Limit','D/C','Result'],checks.map(c=>[e(c.title),f(c.demand,c.quantity??'ratio'),f(c.capacity,c.quantity??'ratio'),c.utilization?.toFixed(3)??'-',`<b class="${c.status}">${e(statusText(c.status))}</b>`]),'checks'):'';
 const selected=(groups:string[])=>s.checks.filter(c=>groups.includes(c.group));
const statusText=(status:CheckResult['status'])=>status==='excluded'?'BY OTHERS':status;
 const eq=(id:string)=>{const c=s.checks.find(c=>c.id===id);return c?`<div class="equation"><b>${e(c.title)}</b>${math(c.equation)}<p>${e(c.note)}</p><small>${c.referenceIds.map(id=>{const ref=references.find(v=>v.id===id);return e(`${ref?.title} ${ref?.clause}`);}).join('; ')}</small></div>`:'';};
 const sketch=(name:string)=>{const v=engineeringSketches(s).find(v=>v.name===name);return v?`<div class="drawing">${drawingSvg(v)}</div>`:'';};
 const pageFigureTopics:Record<string,string[]>={
  '01':['Project'], '02':['Loading','Criteria'],
  '03':['Strength','Serviceability','Local forces','Bracing'],
  '03A':['Section'], '03B':['Cap channel'],
  '04':['Connections'], '04A':['Detailing'], '04B':['Column bracket'],
  '04C':['Column bracket'], '04D':['Fatigue'],
  '04E':['Flange attachment'], '04F':['Fatigue'],
  '05':['Rail details','Fatigue'], '06':['Interfaces','Analysis'],
  '07':['Geometry','Detailing'], '08':['Local forces'], '09':['Connections'],
  '10':['Project'], '11':['Interfaces']
 };
 const page=(title:string,body:string)=>`<section class="page${title.startsWith('Appendix')?' equation-appendix':''}"><div class="running">CRANECALC / ${e(p.number)} <span>${demo?'FICTITIOUS DEMONSTRATION':'RUNWAY DESIGN'} / ${e(s.revision)}</span></div><h2>${title}</h2>${title.startsWith('Appendix')?'':`<div class="report-figure-strip">${(title.includes('Fatigue register')?['Fatigue']:pageFigureTopics[title.split(' / ')[0]]??['Project']).map(topic=>checkFigureHtml(topic,p)).join('')}</div>`}${body}</section>`;
 const failed=s.checks.filter(c=>c.status==='fail'),governing=[...s.checks].filter(c=>c.utilization!==undefined&&!['Analysis','Loading','Criteria','Detailing'].includes(c.group)).sort((a,b)=>b.utilization!-a.utilization!).slice(0,6);
 const keeper=r.fatigue.filter(f=>f.id.startsWith('RC')).sort((a,b)=>b.damage-a.damage)[0];
 const fatigueOverview=`<h3>Fatigue register basis</h3><p>${d.fatigueDetails.map(v=>e(v.id+": "+v.name)).join("; ")}.</p><p>Every rail-keeper station and both flange edges are checked automatically. Governing keeper ${e(keeper?.id)} at x=${f(keeper?.x)}: range ${f(keeper?.range,'stress')}, damage ${keeper?.damage.toFixed(4)}, peak with dead load ${f(keeper?.peak,'stress')}. The register also checks each entered fatigue point. Capped members add Category B continuous-weld base metal at all keeper stations and Category E end-termination bounds; the complete worksheet retains every station.</p><p>Signed empty/loaded/absent stress extrema include biaxial bending and warping; half side thrust is reversed. Local keeper flange bending uses each bin’s unfactored wheel loads and reversed half side thrust, without impact; its full reversed range is superposed conservatively. All bins contribute to Miner damage without threshold credit, and the largest range is additionally assigned to all cycles. Weld roots use C-double-prime, throats use F; the peak bound is 0.66Fy.</p>`;
 const pages:string[]=[];
 pages.push(page('01 / Basis, inputs & review summary',`<h1>${e(p.title)}</h1><div class="notice"><b>${demo?'CAPABILITY DEMONSTRATION - FICTITIOUS INPUTS':'PROJECT CALCULATION'}</b><p>${demo?'Realistic fictitious loads, materials and owner criteria demonstrate the software workflow. This is not a site-specific construction or fabrication package.':'Use only with the actual supplier schedule and coordinated project drawings.'}</p></div><p><b>Scope:</b> one runway line, ${p.section.kind==='cap'?'channel-capped W girder':'rolled girder'}, rail, both-flange ties and defined girder-side connection templates. ${usesExistingBracket(p)?'New bolted seat checks and documented existing bracket assessment are included. Existing steel resistance is supplied by the recorded engineer assessment, not calculated here.':d.bracket?.enabled?'Welded gravity brackets, root welds and receiving-column local checks are included.':'Column brackets are excluded.'} Global building framing, anchors, building-mounted end stops and foundations are excluded. The 3D building and hardware remain reference geometry.</p><p><b>Basis:</b> Reference AIST Technical Report 13 (supplied source dated February 24, 2020); AISC 360-16; AISC Design Guide 7, third edition with February 2023 errata. ASCE 7-16 building actions are outside this runway-only calculation.</p>${table(['Input','Value','Input','Value'],[
 ['Member',e(p.section.name),'Method / system',`${p.method} / ${p.system}`],['Spans',p.spans.map(v=>f(v)).join(' / '),'Fy / Fu',`${f(p.section.Fy,'stress')} / ${f(p.section.Fu,'stress')}`],['Top / bottom ties',`${f(p.lateralBraceSpacing)} / ${f(p.aist!.bottomBraceSpacing)}`,'Unbraced length',f(p.unbracedLength)],['Girder / rail weight',`${f(prop.weight,'lineLoad')} / ${f(p.railWeight,'lineLoad')}`,'Additional dead load',f(p.deadLoad,'lineLoad')],['Rail head above flange',f(p.railHeight),'Rail eccentricity',f(p.railEccentricity)],['Building class / repetitions',`${p.aist!.buildingClass} / ${p.aist!.buildingCycles.toLocaleString()}`,'Fatigue fluctuations',p.fatigue.cycles.toLocaleString()],['Vertical / lateral limits',`L/${p.verticalLimit} / L/${d.criteria.railLateralLimit}`,'Twist limit',`${d.criteria.twistLimit} rad`],['Nominal rail gauge',f(d.criteria.railGauge),'Camber / level tolerance',`${f(p.aist!.camber)} / ${f(d.criteria.levelTolerance)}`]])}<h3>${failed.length?`${failed.length} FAILED CHECKS - review required`:'Governing checks'}</h3>${numeric(failed.length?failed:governing)}${s.checks.some(c=>c.status==='excluded')?`<div class="notice"><b>OUTSIDE THIS CALCULATION - BY OTHERS</b><p>${s.checks.filter(c=>c.status==='excluded').map(c=>e(c.title)).join('; ')}. These items are required for the installation but are not checked in this package; see each item for the forces and scope.</p></div>`:''}<p>${s.checks.length} calculated/applicability checks. Equilibrium and both refinement gates pass before export. A failed engineering check may be documented in an exported report; exporting does not make that check acceptable.</p><small>Created ${e(s.createdAt)}. Source register ${e(s.referenceVersion)}. The project JSON and signed interface CSV are available with this revision.</small>${connectionCoordination(p).length?'<p><b>MODEL COORDINATION REQUIRED: TIE HARDWARE INTERFERES WITH GIRDER / STIFFENERS. SEE SECTION 11.</b></p>':''}<h3>Fatigue summary</h3><p>All keeper stations, both flange edges and ${d.fatigueDetails.length} entered material points are checked. Governing keeper ${e(keeper?.id)}: range ${f(keeper?.range,'stress')}; damage ${keeper?.damage.toFixed(4)}. Section 05 lists duty-level forces and the fatigue register. Local loads are unfactored without impact; full reversal and all-cycle bounds remain.</p>`));
 pages.push(page('02 / Crane schedule & load combinations',p.cranes.map((c,i)=>`<h3>Crane ${i+1}: ${e(c.name)}</h3><p>${e(c.loadSource)}</p>${table(['Wheel','Offset','Loaded static','Empty','Side thrust'],c.wheels.map((w,i)=>[i+1,f(w.offset),f(w.loaded/(c.includesImpact?1+c.impact:1),'force'),f(w.unloaded,'force'),f(w.lateral,'force')]))}<p>Impact ${(c.impact*100).toFixed(0)}%; longitudinal ${f(c.longitudinal,'force')}; rated lift ${f(c.design?.ratedLoad,'force')}; trolley ${f(c.design?.trolleyWeight,'force')}; bridge ${f(c.design?.bridgeWeight,'force')}. Travel origin ${f(c.travelStart)} to ${f(c.travelEnd)}. Side share ${c.design?.sideShare}; ${e(c.design?.distributionSource)}.</p>`).join('')+`<h3>Projected ${p.method} combinations</h3><p>Dead, lift and impact are separated. Empty, loaded and absent states are evaluated; side thrust acts from one crane at a time with both signs. Values below are independent envelopes within a combination. H1 interaction and interface rows retain concurrency.</p>${table(['Combination','Mx','Shear','Reaction','Axial','H1 D/C'],a.combinations.map(c=>[`${e(c.id)} ${math(c.equation)}`,f(c.moment,'moment'),f(c.shear,'force'),f(c.reaction,'force'),f(c.axial,'force'),c.interaction.toFixed(3)]),'combos')}<p>All ${selected(['Loading','Criteria']).length} load-basis and owner-classification checks are listed in the complete worksheet. Minimum impact, side thrust, traction and input decomposition are checked before export.</p>${numeric(selected(['Loading','Criteria']).filter(c=>c.status==='fail'))}<p>Reference AIST Technical Report 13 §§3.6.2-3.6.3 and 3.10.2.1-3.10.2.4. Bumper action is transferred directly to the excluded building-mounted stop; it is not omitted from the interface schedule.</p>`));
 pages.push(page('03 / Girder, torsion & serviceability',numeric(selected(['Strength','Serviceability','Local forces','Bracing']))+eq('torsion-normal')+eq('rail-head')+`<p><small>Vlasov model: wheel/restraint nodes, free support warping, finite tie stiffness, 0.8 elastic stiffness for strength. AISC F2/capped F5 and H1 also apply. Governing normal stress: ${e(r.governing.normalStress?.combination)}, x=${f(r.governing.normalStress?.x)}, case ${e(r.governing.normalStress?.id)}. Distortion and building flexibility excluded.</small></p>`));
 if(p.section.kind==='cap'&&p.capDesign){
  const c=p.capDesign,m=cappedMechanics(p.section)!,strength=girderStrength(p,prop);
  pages.push(page('03A / Capped girder properties & stability',`<p><b>${e(p.section.name)}</b>. ${e(c.materialSource)}. CMAA ${e(c.cmaaClass)}: ${e(c.dutySource)}.</p>${table(['Property / input','Value','Property / input','Value'],[
   ['Channel Fy / Fu',f(c.Fy,'stress')+' / '+f(c.Fu,'stress'),'Electrode',f(c.Fexx,'stress')],['Top / bottom Sx',f(m.Stop,'modulus')+' / '+f(m.Sbottom,'modulus'),'Top lateral It',f(m.topI,'inertia')],['Centroid above bottom',f(m.elastic.cy),'Shear center above bottom',f(m.shearCenter)],['Cw (integrated)',f(m.Cw,'warping'),'J (component sum)',f(m.J,'inertia')],['Top / bottom tie offset from shear center',f(m.topOffset)+' / '+f(m.bottomOffset),'Monosymmetry beta',f(m.beta)],['Cap fillet / development',f(c.weldSize)+' / '+f(c.developmentLength),'Assembly mass per length',e(formatSectionMass(m.nominalWeight,p.units))]
  ])}<p>Full-length cap with continuous dual fillets and unperforated top elements. Fit-up: ${e(c.fitupNote)}. Bearing stiffeners require CJP welds to the W top flange.</p><h3>Separate compression-flange branches</h3>${table(['Compression side','rt','Lp','Lr (F5)','Nominal Mn'],strength.capDirections!.map((v,i)=>[i?'Bottom W flange':'Top flange + channel',f(v.rt),f(v.Lp),f(v.Lr),f(v.Mn,'moment')]))}<p>The lower resistance of the two bending signs is used everywhere, including simple spans. Cb=1, lower steel grade, elastic lateral resistance and no plastic reserve. F5 Lr is used consistently; the F4 Lr in DG7 Table A-2 is not mixed with F5 stress equations. E4-3 includes the centroid-to-shear-center offset; E7 conservatively applies the least plate effective-width ratio to the entire axial area.</p>${eq('major')}${eq('minor')}<p>The open median-line model merges the contacting flange and cap web; small plate-centerline offsets have zero area. Fillets and the positive composite-overlap contribution to J are omitted. Loads, finite top/bottom restraint springs, normal warping stress and warping shear use the calculated shear center and sectorial coordinates. Local distortion caused by gaps is outside this model.</p>`));
  const normalWeld=r.fatigue.filter(v=>v.id.startsWith('CW')).sort((a,b)=>b.damage-a.damage)[0];
  pages.push(page('03B / Cap attachment strength & fatigue',numeric(selected(['Cap channel']).filter(c=>c.demand!==undefined))+`<p><b>Applicability:</b> ${selected(['Cap channel']).filter(c=>c.demand===undefined).map(c=>e(c.title)+': '+e(statusText(c.status))).join('; ')}.</p>`+eq('cap-weld-strength')+eq('cap-development')+eq('cap-weld-fatigue')+`<p>Governing continuous-weld base metal: ${e(normalWeld?.id)}, Category B, range ${f(normalWeld?.range,'stress')}, damage ${normalWeld?.damage.toFixed(4)}. Category E cap-end details appear in the fatigue register. Local keeper bending uses the channel web alone; W flange thickness is not added to it. Drawing S-03 shows the continuous cap welds and both end development regions.</p>`));
 }
 pages.push(page('04 / Girder-side connections',`<p>Symmetric double-cover plates transfer in-plane forces through two bolt shear/slip planes. No out-of-plane tension or prying is credited. Both flanges have paired flat-bar ties. End covers are conservatively checked for full vertical reaction plus longitudinal action; fitted bearing plates carry gravity.</p>${numeric(selected(['Connections']))}<p>AISC 360-16 J2-J4, J7, J10.8; Appendix 6. Both cover and central plies are checked. See SK-04 to SK-06 for dimensions, bolts, weld lengths, projection and effective gusset length.</p>`));
 if(p.system==='simple'){
  const c=simpleSupportInput(p);
  pages.push(page('04A / Independent girder ends at shared supports',`<p>Each bay has independent bearings and separate flange ties to the column. Its left end transfers longitudinal force; its right end slides. Neither end transfers moment across the joint. Cap channels stop with their girders. Reference AIST Technical Report 13 §5.8.1.</p>${table(['Input','Value'],[['Clear girder gap',f(c.endGap)],['Sliding travel, each direction',f(c.guideTravel)],['Temperature rise / fall from erection',`${f(c.temperatureRise,'temperatureChange')} / ${f(c.temperatureFall,'temperatureChange')}`],['Setting tolerance at each end',f(c.settingTolerance)]])}${numeric(s.checks.filter(c=>c.id.startsWith('simple-')))}${eq('simple-joint-gap')}${eq('simple-guide-travel')}<h3>Shared bracket reactions</h3><p>Values below occur together at the case of maximum combined downward reaction at each grid. Seat moment is the sum of downward end reactions times their signed bearing offset from the grid; positive offset runs toward the next grid. Individual girder-end extrema and lateral/longitudinal cases are retained in the signed interface CSV.</p>${table(['Grid','Station','Left girder V','Right girder V','Combined V','Seat ΣV·dx'],sharedSupportRows(s).map(({grid,x,row})=>[grid,f(x),f(row?.ends?.filter(v=>v.end==='right').reduce((a,v)=>a+v.vertical,0),'force'),f(row?.ends?.filter(v=>v.end==='left').reduce((a,v)=>a+v.vertical,0),'force'),f(row?.vertical,'force'),f(row?.seatMoment,'moment')]))}<p>Analysis retains the grid-to-grid span. Actual bearings are inset and the bracket receives the eccentric load locations shown on S-04. Girder-side bearing/stiffener checks retain the combined reaction as a conservative bound for each end.</p><p><b>Receiving connection design:</b> ${usesExistingBracket(p)?'The new seat and existing support assessment are checked below. The full column,':d.bracket?.enabled?'The welded bracket/spreader is checked below. The full column,':'The bracket/spreader, column,'} locating/guide attachments, uplift load path and longitudinal flexibility of the ties require project design. The double-cover checks establish girder-side in-plane resistance only; they do not establish articulation or a complete sliding hold-down design.</p><p>When a crane straddles a joint, its full traction is assigned to each occupied bay in separate bounding scenarios, identified by T plus the bay number in the case ID. No drive-wheel distribution is assumed and alternative scenarios must not be added.</p>`));
 }
 if(usesExistingBracket(p)&&r.existingBracket){
  const eb=existingBracket(p),b=d.bracket!,br=r.existingBracket,rows=s.checks.filter(c=>c.id.startsWith('existing-'));
  pages.push(page('04B / Existing brackets and new bolted seats',`<p>New runway bearings and a bolted spreader sit on a surveyed existing I-bracket. Column continuity plates and original root welds are existing construction. Section geometry does not establish bracket or connection capacity.</p>${table(['Survey input','Value','New work','Value'],[['Bracket type / section',e(existingBracketLabel(b)),'',''],['Existing bracket depth',f(eb.depth),'New plate length',f(b.seatLength)],['Existing flange width',f(eb.width),'New plate projection',f(b.seatProjection)],['Existing bracket projection',f(eb.projection),'New plate thickness',f(b.seatThickness)],['Existing flange / web',`${f(eb.flangeThickness)} / ${f(eb.webThickness)}`,'Column face to runway',f(b.reach)],['Continuity plate thickness',f(eb.continuityThickness),'Seat bolts',`4 - ${f(eb.bolts.diameter)} ${e(eb.bolts.grade)}`]])}<p><b>Survey:</b> ${e(eb.geometrySource)}<br/><b>Existing support assessment:</b> ${e(eb.rating.source)}<br/><b>Capacity basis:</b> ${eb.rating.method}; available resistances, not nominal strengths.</p><h3>Concurrent actions at governing assessment interaction</h3>${table(['Station','Case','Vertical','Root moment bound','Seat eccentric moment'],br.stations.map(v=>[f(v.x),e(v.caseId),f(v.vertical,'force'),f(v.rootMoment,'moment'),f(v.seatMoment,'moment')]))}<p>Strength includes new plate and existing bracket self-weight at 1.4 LRFD / 1.0 ASD. The bracket carries gravity; flange ties and locating/sliding attachments have separate horizontal paths. Root moment uses the far edge of each bearing patch. Existing capacity is not inferred from continuity plates or the photo.</p>${eq('existing-interaction')}`));
  pages.push(page('04C / New seat and existing support verification',numeric(rows.filter(c=>!c.id.includes('fatigue')))+eq('existing-seat-flexure')+eq('existing-seat-deflection')+`<p>Seat bolts retain the new plate. No structural hold-down, friction or moment continuity is credited. The recorded attachment assessment covers bolt resistance, hole effects and erection loads. Original bracket welds are not specified as new field welds. Existing bracket/column service deformation and movement remain assessment inputs.</p>`));
  pages.push(page('04D / Existing support and seat fatigue',numeric(rows.filter(c=>c.id.includes('fatigue')))+table(['Duty bin','Cycles','Seat stress range','Vertical range','Root moment range','Eccentric moment range'],br.fatigue.map(v=>[e(v.name),v.cycles.toLocaleString(),f(v.seatStress,'stress'),f(v.vertical,'force'),f(v.rootMoment,'moment'),f(v.seatMoment,'moment')]))+eq('existing-fatigue')+eq('existing-seat-fatigue')));
 }
 if(d.bracket?.enabled&&r.bracket){
  const b=d.bracket,br=r.bracket,all=s.checks.filter(c=>c.group==='Column bracket'),strength=all.filter(c=>!c.id.startsWith('bracket-fatigue')&&!c.id.startsWith('bracket-column')&&!['bracket-deflection','bracket-rotation','bracket-tr13-load','bracket-uplift'].includes(c.id));
  pages.push(page('04B / Welded bracket inputs & load path',`<p>Two rectangular plate ribs, welded directly to the receiving column flange, support a common seat. Vertical reactions of adjacent girders are applied together at their actual bearing offsets. Lateral/longitudinal ties have independent column connections. Bracket strength does not verify those receiving attachments, the whole column, frame or foundations.</p>${table(['Input','Value','Input','Value'],[
   ['Face to runway center',f(b.reach),'Seat projection',f(b.seatProjection)],['Seat length / thickness',f(b.seatLength)+' / '+f(b.seatThickness),'Rib depth / thickness',f(b.ribDepth)+' / '+f(b.ribThickness)],['Rib spacing',f(b.ribSpacing),'Root / seat fillet',f(b.rootWeld)+' / '+f(b.seatWeld)],['Column d / bf',f(b.receiver.depth)+' / '+f(b.receiver.width),'Column tf / tw',f(b.receiver.flangeThickness)+' / '+f(b.receiver.webThickness)],['Column Fy / Fu',f(b.receiver.Fy,'stress')+' / '+f(b.receiver.Fu,'stress'),'Column flange unbraced length',f(b.receiver.unbracedLength)],['Other concurrent column axial',f(b.receiver.axialDemand,'force'),'Deflection / rotation limits',f(b.deflectionLimit)+' / '+b.rotationLimit+' rad']
  ])}<p><b>Receiver source:</b> ${e(b.receiver.source)}.</p><h3>Simultaneous bracket actions at maximum rib force</h3>${table(['Station','Combined V','Seat moment','Left rib','Right rib','Root moment'],br.stations.map(v=>[f(v.x),f(v.vertical,'force'),f(v.seatMoment,'moment'),f(v.leftRib,'force'),f(v.rightRib,'force'),f(v.rootMoment,'moment')]))}<p>Signed rib force: compression/gravity positive, tension negative. Self-weight of the complete bracket is added at 1.4 LRFD / 1.0 ASD. Transverse eccentricity uses the far edge of the bearing patch. Each rib is checked separately, without favorable plate-flange composite action. Alternative sampled cases are not additive.</p>${eq('bracket-rib-flexure')}${eq('bracket-seat-flexure')}`));
  pages.push(page('04C / Welded bracket strength & welds',numeric(strength)+eq('bracket-root-weld')+eq('bracket-root-base')+`<p>Rib shear and conservative elastic normal/shear interaction are checked in addition to F11 bending. All root welds are continuous on both sides of each rib. Seat weld strength credits only the bearing-patch length. The actual seat and rib dimensions appear on ARCH D sheet S-05.</p>`));
  pages.push(page('04D / Bracket fatigue, service & local receiver',numeric(all.filter(c=>!strength.includes(c)))+table(['Duty bin','Cycles','Rib range','Seat range','Root weld range','Seat weld range'],br.fatigue.map(v=>[e(v.name),v.cycles.toLocaleString(),f(v.rib,'stress'),f(v.seat,'stress'),f(v.rootWeld,'stress'),f(v.seatWeld,'stress')]))+`<p>Unfactored fatigue-bin loads exclude impact. Full reversal of each maximum absolute response bounds redistribution between ribs. Base metal uses conservative E-prime with transverse-fillet root reduction and Miner summation; weld throats use Category F and the largest range for all cycles. Existing column fatigue under combined building/crane stresses requires the building model.</p>${eq('bracket-column-panel')}<p>Local receiver checks include J10 flange bending, web yielding/crippling, sidesway buckling and panel shear with axial reduction. These checks require the confirmed entered section and a continuously connected web/flange. No continuity-plate credit is taken. Column global stability, foundation resistance and deformation of the building interface remain separate.</p>`));
 }
 if(flangeTieGeometry(p)){
  const g=flangeTieGeometry(p)!,t=d.brace,at=g.attachment;
  pages.push(page('04E / Direct flange attachment',`<p>Tie bars are shifted away from bearing stiffeners; top bars clear the cap legs. Girder gussets connect through saddle plates directly to the W flanges. No holes or cuts are made in the cap or flanges. See ARCH D S-06.</p>${table(['Input','Value','Input','Value'],[['Tie length / width',f(t.length)+' / '+f(t.width),'Bar / gusset thickness',f(t.thickness)+' / '+f(t.gussetThickness)],['Setback toward girder end',f(at.longitudinalSetback),'Saddle length / thickness',f(at.saddleLength)+' / '+f(at.saddleThickness)],['Effective flange weld length',f(g.rootLength),'Saddle / gusset fillet',f(at.weldSize)],['Top / bottom force offset',f(g.topDrop)+' / '+f(g.bottomDrop),'Unrestrained bar length',f(g.freeLength)]])}${numeric(selected(['Flange attachment']).filter(c=>!c.id.includes('fatigue')))}<p>Elastic strip and weld-group bounds; no plastic redistribution or composite saddle/flange credit. Local attachment compliance is added to the brace flexibility. Analysis retains conservative full grid-to-grid spans and idealized end-zone restraint stations. Physical end offsets appear on the drawings.</p>`));
  pages.push(page('04F / Flange attachment fatigue & scope',numeric(selected(['Flange attachment']).filter(c=>c.id.includes('fatigue')))+eq('flange-tie-saddle')+eq('flange-tie-flange')+`<p>Saddle edge points at both flanges are included in the fatigue register. Their global stress ranges are combined with the full local flange-strip range, assigned conservatively to every duty bin. Category E-prime is used without endurance credit.</p><div class="notice"><b>MOVEMENT AND GLOBAL BUILDING INTERFACE REMAIN SEPARATE</b><p>These checks establish local resistance and static fit. They do not verify rigid tie roots for thermal movement, end rotation or column shortening. Sliding/locating and hold-down attachments, global column forces, frame deformation and supplier rail hardware require project-specific design before fabrication.</p></div>`));
 }
 const fatigueExplicit=s.checks.filter(c=>c.group==='Fatigue'&&!c.id.startsWith('detail-fatigue-')&&!c.id.startsWith('detail-full-cycle-')&&!['fatigue','fatigue-peak','end-weld-fatigue'].includes(c.id));

 pages.push(page('05 / Rail details & fatigue',numeric(selected(['Rail details']))+table(['Fatigue duty bin','Cycles','Vertical group','Lateral group','Local flange range','Weld range'],r.railFatigueBins.map(b=>[e(b.name),b.cycles.toLocaleString(),f(b.vertical,'force'),f(b.lateral,'force'),f(2*b.flangeStress,'stress'),f(2*b.weldStress,'stress')]))+`<p>Reference AIST Technical Report 13 §3.10.2.3: unfactored Cds + lift fraction × Cvs + 0.5Css, no impact. Full reversal bounds above use each duty bin’s wheel groups; no load-sharing credit. Girder detail ranges also include global bending and warping.</p>`+numeric(fatigueExplicit)+`<p>The following fatigue register identifies each entered material point. Automatically generated rail-keeper stations are summarized on page 01 and retained in the complete worksheet.</p>`));
 const stops=selected(['End stops']).filter(c=>c.status!=='not-applicable');
 if(stops.length)pages.push(page('05A / Runway end stops',`<p>Bolted stops at both ends of each runway, over the end bearings (sheet S-07). The crane bumper force, factored by the AIST stop combinations, acts at the bumper height on the face plate. The front bolts resist the overturning about the heel of the base plate in tension with shear; the base plate and girder flange are checked for no prying. The bumper acts above the girder centroid, so the end couple is added to the girder stop combinations and to the far-support uplift.</p>`+numeric(stops)));
 const fatiguePoints=r.fatigue.filter(f=>!f.id.startsWith('RC')&&!f.id.startsWith('CW'));
 const fatigueRowsPerPage=14;
 for(let start=0;start<fatiguePoints.length;start+=fatigueRowsPerPage){
  pages.push(page(`05 / Fatigue register${start?' - continued':''}`,`<p>Signed stress ranges at entered material points. All-cycle limits apply the largest range to every fluctuation; damage includes every duty bin. Positions are measured from grid 1 along the calculated runway.</p>`+table(['Material point','Category','Range','All-cycle limit','Damage','Peak'],fatiguePoints.slice(start,start+fatigueRowsPerPage).map(v=>[e(v.id)+`<br/>x=${f(v.x)}`,e(v.category),f(v.range,'stress'),f(s.checks.find(c=>c.id===`detail-full-cycle-${v.id}`)?.capacity,'stress'),v.damage.toFixed(4),f(v.peak,'stress')]))+(start+fatigueRowsPerPage>=fatiguePoints.length?fatigueOverview:'<p>Material-point register continues on the next page.</p>')));
 }
 // Retain concurrent rows governing any signed component at each support.
 const rows=new Map<string,typeof r.interfaces[number]>();
 for(const x of [...new Set(r.interfaces.map(v=>v.x))])for(const component of ['vertical','top','bottom','longitudinal','torque'] as const)for(const sign of [-1,1]){const v=r.interfaces.filter(v=>v.x===x).sort((a,b)=>sign*(b[component]-a[component]))[0];if(v)rows.set(`${v.x}:${v.id}:${v.longitudinal}`,v);}
 const interfaceRows=[...rows.values()];
 for(let start=0;start<interfaceRows.length;start+=14){
  const last=start+14>=interfaceRows.length;
  pages.push(page(`06 / Forces delivered to excluded structure${start?' - continued':''}`,`<p>Factored AIST runway combinations (${p.method}). For building checks with roof, snow, wind and seismic loads use the unfactored reactions by load type on page 06A. Each row is a simultaneous signed force set. Positive vertical acts down on the building; positive top/bottom lateral values act in the positive side-thrust direction. Longitudinal sign is listed both ways. Do not combine independent column maxima. Torques are about the shear center (centroid for symmetric W sections). Transfer the force system to the building connection datum before designing that structure. Interface stiffness is assumed fixed beyond the modeled girder-side connections.</p>${table(['x','Combination / crane origins','V','H top','H bottom','Long.','Torque'],interfaceRows.slice(start,start+14).map(v=>[f(v.x),`${e(v.combination)}<br/>${v.cranes.map(c=>`C${c.index+1}@${f(c.origin)} ${c.loaded?'loaded':'empty'}`).join('; ')}; side ${v.lateralSign>0?'+':'-'}`,f(v.vertical,'force'),f(v.top,'force'),f(v.bottom,'force'),f(v.longitudinal,'force'),f(v.torque,'moment')]),'interfaces')}${last?`<h3>Separate full-speed end-stop demand</h3>${table(['Crane','Longitudinal bumper force','Load path'],p.cranes.map(c=>[e(c.name),f(c.design?.bumperForce,'force'),'Direct to building-mounted stop; girder bypass. Stop, building and foundation resistance excluded; the enabled runway bracket is a separate gravity path.']))}<p>Complete coincident rows by combination are preserved in the downloadable interface CSV. These tables retain the rows governing signed extrema across combinations at each station.</p>${numeric(selected(['Analysis']))}`:`<p>Signed interface forces continue on the next page. Complete coincident rows are retained in the interface CSV.</p>`}`));
 }
 if(s.supportReactions){
  const sr=s.supportReactions;
  pages.push(page('06A / Existing building: support reactions by load type',`<p>Unfactored reactions for checking the building that carries the runway, downward positive. Cd, Cv and Ci come from the crane arrangement that maximizes them at each support (order and separation respected; governing AIST/ASCE 7 impact). Css is the largest single-crane side thrust at the support, at the rail head, taken with the vertical maximum. Under ASCE 7 §4.9 every crane component is live load L.</p>`+table(['Station','D','L','Crane empty Cd','Lifted Cv','Impact Ci','Side thrust Css','Least crane'],sr.supports.map(v=>[f(v.x),f(v.D,'force'),f(v.L,'force'),f(v.Cd,'force'),f(v.Cv,'force'),f(v.Ci,'force'),f(v.Css,'force'),f(v.craneMinimum,'force')]),'checks')+`<p>Runway longitudinal force Cls = ${f(sr.Cls,'force')} (largest single crane, governing minimum), delivered at the locating support or to the building bracing.</p>`));
 }
 if(s.existingColumn&&p.existingColumn){
  const c=p.existingColumn,x=s.existingColumn,top=[...x.combinations].sort((a,b)=>b.U-a.U).slice(0,8);
  pages.push(page('06B / Existing column check',table(['Item','Value','Item','Value'],[['Section',e(x.source),'Fy',f(p.details?.bracket?.enabled?p.details.bracket.receiver.Fy:c.Fy,'stress')],['Base to top support',f(c.height),'Base to seat',f(c.seatElevation)],['Rail head above base',f(x.railElevation),'Eccentricity',f(x.eccentricity)],['Strong axis',`${c.strong.base} base, ${c.strong.top} top`,'Weak axis',`${c.weak.base} base, ${c.weak.top} top`],['Lcx / Lcy',`${f(c.Lcx)} / ${f(c.Lcy)}`,'Lcz / Lb',`${f(c.Lcz)} / ${f(p.details?.bracket?.enabled?p.details.bracket.receiver.unbracedLength:c.Lb)}`],['Longitudinal force',c.longitudinal==='column'?'resisted by this column':'building bracing','Governing support',f(x.station)]])
   +`<h3>Existing load effects at the governing section (unfactored) - ${e(c.source)}</h3>`+table(['Load','P','Mx','My','V'],(['D','L','Lr','S','R','W','E'] as const).map(k=>[k,f(c.existing[k].P,'force'),f(c.existing[k].Mx,'moment'),f(c.existing[k].My,'moment'),f(c.existing[k].V,'force')]),'checks')
   +`<h3>Governing ASCE 7 ${p.method} combinations (crane as live load L)</h3>`+table(['Case','Combination','Pr','Mrx','Mry','B1x','H1'],top.map(k=>[e(k.id),e(k.equation),f(k.P,'force'),f(k.Mx,'moment'),f(k.My,'moment'),k.B1x.toFixed(3),k.U.toFixed(3)]),'checks')
   +`<p>Governing H1 ratio by support (same column at every support): ${x.bySupport.map(v=>`x = ${f(v.x)}: ${v.U.toFixed(3)}`).join('; ')}. Results above are for x = ${f(x.station)}.</p>`
   +numeric(selected(['Existing column']))+`<p>Single-column elastic model per axis; existing moments are added to the crane peaks without sign or location credit. Frame action, base flexibility, the column-side connections of brackets and ties, bracing, anchors and foundations are verified separately.</p>`));
 }
 if(s.longitudinalBracing&&p.longitudinalBracing){
  const b=p.longitudinalBracing,x=s.longitudinalBracing,top=[...x.combinations].sort((a,c)=>c.force-a.force).slice(0,6);
  pages.push(page('06C / Crane-level longitudinal bracing',table(['Item','Value','Item','Value'],[['System',b.system==='rod-x'?'Rod X, tension only':b.system==='angle-x'?'Angle X':'Single angle','Member',e(x.member.description)],['Braced bays on line',String(b.bays),'Tiers per bay',String(b.tiers)],['Bay width',f(b.bayWidth),'Base to work point',f(b.height)],['Diagonal length',f(x.length),'Diagonals sharing shear',String(x.diagonals)],['Crane traction Cls',f(x.Cls,'force'),'Crane stop Cbs',x.Cbs?f(x.Cbs,'force'):'not on this bracing'],['Existing W',f(b.existing.W,'force'),'Existing E',f(b.existing.E,'force')]])
   +`<h3>Governing combinations (line force H, diagonal force) - ${e(b.source)}</h3>`+table(['Case','Combination','H on line','Diagonal'],top.map(k=>[e(k.id),e(k.equation),f(k.H,'force'),f(k.force,'force')]),'checks')
   +numeric(selected(['Longitudinal bracing']))+`<p>Crane loads are live load L (ASCE 7 §4.9); the AIST crane stop case uses ${p.method==='LRFD'?'1.0':'0.67'}Cbs without wind or seismic. Per braced bay the columns take ±${f(x.foundation.axial,'force')} from overturning and the foundation ${f(x.foundation.shear,'force')} base shear. Collectors, brace connections, braced-bay columns, anchors and foundations are verified separately.</p>`));
 }
 pages.push(page('07 / Girder arrangement & detailing criteria',sketch('runway-elevation')+table(['Section property','Value','Section property','Value'],[['A',f(prop.A,'area'),'Ix / Iy',f(prop.Ix,'inertia')+' / '+f(prop.Iy,'inertia')],['Sx / Sy',f(prop.Sx,'modulus')+' / '+f(prop.Sy,'modulus'),'J / Cw',f(prop.J,'inertia')+' / '+f(prop.Cw,'warping')],['Depth / flange width',f(p.section.d)+' / '+f(p.section.bf),'Flange / web thickness',f(p.section.tf)+' / '+f(p.section.tw)]])+numeric(selected(['Detailing']))+``));
 pages.push(page('08 / Bearing & end connection',sketch('bearing-detail')+sketch('end-connection-detail')));
 pages.push(page('09 / Flange tie & rail joint',sketch('tie-connection-detail')+sketch('rail-detail')));
 const used=new Set(s.checks.flatMap(c=>c.referenceIds));
 const refGroups=new Map<string,{title:string;clauses:string[];url:string}>();for(const ref of references.filter(ref=>used.has(ref.id))){const key=ref.url||ref.id;const g=refGroups.get(key)??{title:ref.title,clauses:[],url:ref.url};g.clauses.push(ref.clause);refGroups.set(key,g);}
 pages.push(page('10 / Fabrication, sources & limitations',Object.entries(d.fabrication).map(([k,v])=>`<h3>${e(k)}</h3><p>${e(v)}</p>`).join('')+`<h3>Reference register</h3>${[...refGroups.values()].map(ref=>`<p class="reference"><b>${e(ref.title)}</b> - ${e(ref.clauses.join('; '))}${ref.url?`<br/><a href="${e(ref.url)}">${e(ref.url)}</a>`:''}</p>`).join('')}`));
 pages.push(page('11 / Applicability & project coordination',`${connectionCoordination(p).map(v=>`<div class="notice"><b>CONNECTION LAYOUT REQUIRES REDESIGN</b><p>${e(v)}</p></div>`).join('')}<h3>Connection practice review</h3><p>Column-supported brackets are an established arrangement (Reference AIST Technical Report 13 §5.9.2), new rectangular-rib brackets are custom designs, and existing I-brackets require the recorded project assessment. AISC Design Guide 7 §11.2 requires movement-compatible tiebacks and favors top CJP bearing-stiffener welds, continuous web fillets and fitted bottom ends. The generic keeper is not a proprietary clip. Where enabled, the revised flange saddle and local column tie root are checked in Sections 04E-04F. Rotation/sliding compatibility and the global building interface remain separate. The 3D static hardware scan is separate from strength checks and does not establish fabrication, tool access or moving clearances.</p><p>${e(p.notes)}</p>${p.section.kind==='cap'?'<h3>Capped property model: published comparison</h3><p>The integrated median-line Cw values for twelve reference sections are 7.09-10.89% below Lue/Ellifritt (1993), Table 1. The exact historical-data/model difference remains unresolved; no multiplier is fitted. Closed-form tests verify the implemented idealization, but lower Cw alone does not establish conservative recovered stresses. Review this difference for the project. These comparisons are not permit-package validation. <a href="https://ej.aisc.org/index.php/engj/article/view/604">Original AISC Engineering Journal source</a>.</p>':''}<p>Catalogue rolled W or centered catalogue W + C/MC sections with the dimensioned connection templates. Capped members require full bearing contact, continuous full-length welds and CMAA A-D service; partial/intermittent caps, perforated top elements and CMAA E/F remain outside this model. Supports restrain vertical translation while the girder ends rotate; both flange ties restrain lateral movement through finite springs. Section distortion, seismic/wind load paths and the supporting building are outside this calculation. An actual package additionally needs surveyed existing conditions, supplier-certified wheel/bumper loads and duty, coordinated connection geometry, project-specific rail tolerances, erection sequence and the responsible engineer's approval.</p><p>Independent torsion, stability, bolts and weld-group benchmarks and the earlier twelve-case reference review are software verification evidence. They do not establish project-specific adequacy or resolve differences in public permit calculations.</p>`));
 if(detailed)pages.push(page('Appendix / Complete equation worksheet',[...new Set(s.checks.map(c=>c.group))].map(group=>`<h3 class="check-group-heading">${e(group)}</h3>${checkFigureHtml(group,p)}`+s.checks.filter(c=>c.group===group).map(c=>`<div class="equation"><h3>${e(c.title)} - ${e(statusText(c.status))}</h3>${c.equation?math(c.equation):''}${numeric([c])}${c.substitution?math(c.substitution):''}<p>${e(c.note)}</p><small>${c.referenceIds.map(id=>{const ref=references.find(r=>r.id===id);return e(`${ref?.title} / ${ref?.clause}`);}).join('; ')}</small></div>`).join('')).join('')));
 return `<!doctype html><html><head><meta charset="utf-8"><title>CraneCalc ${e(s.revision)}</title><style>${fonts}
${checkFigureCss}
.report-figure-strip{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.report-figure-strip:has(>.calculation-figure:only-child){display:block}.report-figure-strip>.calculation-figure:only-child{display:flex;text-align:left}.check-group-heading{break-after:avoid}
 @page{size:Letter;margin:16mm 13mm 18mm}*{box-sizing:border-box}body{font:11px/1.35 Arial,sans-serif;color:#1d302c;margin:0}h1{font-size:25px;margin:15px 0}h2{font-size:19px;border-bottom:2px solid #34594e;padding:0 0 8px;margin:16px 0}h3{font-size:12px;margin:15px 0 5px}p{margin:6px 0}.page{margin-bottom:24px}.page>h2{break-after:avoid}.page>.running{display:none}.page.equation-appendix{break-before:page}.running{font-size:9px;letter-spacing:.6px;border-bottom:1px solid #abc1b8;padding-bottom:6px}.running span{float:right}.notice{padding:11px;background:#fff4df;border-left:3px solid #b38336}.notice p{margin-bottom:0}table{width:100%;border-collapse:collapse;table-layout:fixed;margin:9px 0;font-size:10px}th,td{text-align:left;padding:4px 5px;vertical-align:top;border-bottom:1px solid #d6e1dd;overflow-wrap:anywhere}th{background:#eaf1ed;font-weight:600}tr{break-inside:avoid}.checks th:first-child{width:44%}.checks th:nth-child(4){width:9%}.checks th:nth-child(5){width:12%}.checks td{padding:3px 5px}.pass{color:#35614b}.fail{color:#b42318}.not-applicable{font-weight:400;color:#5a6863}.excluded{color:#8a5a00}.equation{break-inside:avoid;padding:8px;border:1px solid #d6e1dd;margin:8px 0}.equation p,small{font-size:9px}.katex{font-size:1.05em}.katex-display{margin:5px 0;overflow:hidden}.combos th:first-child{width:34%}.combos .katex{font-size:.88em}.combos .katex-display{margin:0}.combos td{padding:2px 4px}.drawing{break-inside:avoid;margin:8px 0}.drawing svg{width:100%;height:auto}.interfaces{font-size:9px}.interfaces th:nth-child(2){width:30%}.reference{font-size:9px;break-inside:avoid;margin:6px 0}.reference a{color:#315b50;overflow-wrap:anywhere}
 </style></head><body>${pages.join('')}</body></html>`;
}
