import {format} from './units';
import type { CalculationSnapshot, CheckResult, DesignAnalysis, ProjectInput } from './types';
import { emptyAistInputs, emptyCraneDesign, craneDesignMinimum, minimumSideShare } from './aistLoads';
import { available, concentratedResistance, girderStrength } from './aiscStrength';
import { runwayDesignAnalysis } from './designAnalysis';
import { beamSystem, momentAt } from './beam';
import {cappedElasticProperties} from './capChannel';
import { latexNumber,withinLimit } from './math';
const compared=(id:string,group:string,title:string,demand:number,capacity:number,quantity:CheckResult['quantity'],equation:string,note:string,referenceIds:string[],caseId?:string):CheckResult=>({id,group,title,status:withinLimit(demand,capacity)?'pass':'fail',demand,capacity,quantity,utilization:demand/capacity,equation,substitution:`\\frac{${latexNumber(demand)}}{${latexNumber(capacity)}}=${(demand/capacity).toFixed(4)}`,note,referenceIds,caseId});
const pending=(id:string,group:string,title:string,note:string,referenceIds:string[],status:CheckResult['status']='incomplete',equation=''):CheckResult=>({id,group,title,note,referenceIds,status,equation});
const na=(id:string,group:string,title:string,note:string,referenceIds:string[]):CheckResult=>pending(id,group,title,note,referenceIds,'not-applicable');
const fatigueConstants={A:[25,165],B:[12,110],B1:[6.1,83],C:[4.4,69],D:[2.2,48],E:[1.1,31],E1:[.39,18]} as const;
export function fatigueResistance(category:ProjectInput['fatigue']['category'],cycles:number){const [Cf,Fth]=fatigueConstants[category];return {Cf,Fth,FSR:Math.max(Fth,6900*(Cf/cycles)**(1/3))};}
export function aistChecks(s:CalculationSnapshot):CheckResult[]{
 const p=s.input,props=s.properties!,di=p.aist??emptyAistInputs,L=p.spans.reduce((a,b)=>a+b,0),shortest=Math.min(...p.spans),str= girderStrength(p,props);
 const checks:CheckResult[]=[];
 const compare=(...args:Parameters<typeof compared>)=>checks.push(compared(...args));
 const wait=(...args:Parameters<typeof pending>)=>checks.push(pending(...args));
 const nominalBasis='Reference: AIST Technical Report 13. Runway girder worksheet only; supporting building/frame design is separate.';
 checks.push(di.runwayOnly?{id:'design-scope',group:'Loading',title:'Runway load-path scope',status:'pass',demand:1,capacity:1,utilization:1,quantity:'ratio',equation:'D+C_d+C_v+C_i+C_{ss}+C_{ls}+C_{bs}+L',referenceIds:['tr13-load'],note:`${nominalBasis} Roof, wind, seismic, thermal, fluid and soil effects must be resolved in the building design; these projected combinations apply only where those actions do not load this girder.`}:pending('design-scope','Loading','Runway load-path scope','Confirm that roof, wind, seismic, thermal, fluid and soil loads do not act on this girder. Enter any runway occupancy live load. Building framing shown in 3D is reference geometry.',['tr13-load']));
 const classCycles={D:[0,20000],C:[20000,100000],B:[100000,500000],A:[500000,Infinity]} as const;
 const [lo,hi]=classCycles[di.buildingClass];
 if(!di.classConfirmed||!di.buildingCycles)wait('building-class','Criteria','AIST building classification','Enter owner building load repetitions and confirm the selected A–D building class. These classes differ from CMAA crane service classes and from fatigue stress fluctuations.',['tr13-class']);
 else compare('building-class','Criteria','AIST building classification',di.buildingCycles>=lo&&di.buildingCycles<=hi?0:1, .5,'ratio','N_{building}\\in\\mathcal{N}_{class}',`Owner class ${di.buildingClass}: ${lo.toLocaleString()}–${Number.isFinite(hi)?hi.toLocaleString():'more'} building load repetitions. Boundary counts conservatively permit the adjacent higher class.`,['tr13-class']);
 const missing:string[]=[];
 p.cranes.forEach((c,i)=>{
  const cd=c.design??emptyCraneDesign,min=craneDesignMinimum(c),prefix=`crane-${i+1}`,label=`${c.name} · `;
  if(!cd.splitConfirmed){missing.push(`${c.name}: loaded/unloaded schedules must represent the same trolley position`);wait(`${prefix}-split`,'Loading',label+'Wheel-load decomposition','Confirm that unloaded wheels give crane dead weight at the same trolley position as the loaded schedule. Lifted contribution is loaded static wheel load minus unloaded wheel load; impact is normalized once.',['tr13-load'],'incomplete','P_u=\\gamma_dP_{empty}+\\gamma_v(P_{static}-P_{empty})+\\gamma_i I P_{static}');}
  else compare(`${prefix}-split`,'Loading',label+'Wheel-load decomposition',1,1,'ratio','P_u=\\gamma_dP_{empty}+\\gamma_v(P_{static}-P_{empty})+\\gamma_i I P_{static}',`${p.reportPurpose==='demonstration'?'Fictitious demonstration load split':'Entered manufacturer-confirmed decomposition'}. Crane bridge/trolley dead load and lifted load receive their own combination factors.`,['tr13-load']);
  const pct=(v:number)=>`${+(v*100).toFixed(2)}%`,force=(v:number)=>format(v,'force',p.units,3);
  compare(`${prefix}-impact`,'Loading',label+'Vertical impact',min.impact,Math.max(c.impact,min.impact),'ratio','I_{design}=\\max(I_{supplied},I_{AIST},I_{ASCE})',`${cd.control==='pendant'?'Pendant':`Cab/radio/autonomous ${cd.type}`} operation: AIST Table 3.2 ${pct(min.aist.impact)}, ASCE 7 §4.9.3 ${pct(min.asce.impact)}, supplied ${pct(c.impact)}. Design adopts ${pct(Math.max(c.impact,min.impact))}${c.impact<min.impact?'; the supplied value is below the code minimum and is not used':''}. The supplied-load diagrams retain the entered impact.`,['tr13-crane','asce']);
  if(cd.ratedLoad<=0||cd.trolleyWeight<=0||cd.bridgeWeight<=0||!cd.distributionSource.trim()){
   missing.push(`${c.name}: capacity, trolley/bridge weights and lateral distribution source`);
   wait(`${prefix}-side`,'Loading',label+'Minimum side thrust','Enter crane capacity, trolley and bridge weights, this runway’s side-thrust share and its manufacturer/structural distribution basis. No automatic 50/50 verification is assumed.',['tr13-crane'],'incomplete','C_{ss,total}=\\max(\\eta Q,\\,0.2(Q+T),\\,0.1(Q+T+B))');
  }else{
   const supplied=c.wheels.reduce((n,w)=>n+w.lateral,0),aistRule=cd.control==='pendant'?'0.1(Q+T+B)':cd.type==='stacker'?'\\max(2Q,0.4(Q+T+A),0.15(Q+T+B+A))':'\\max(\\eta Q,0.2(Q+T),0.1(Q+T+B))';
   compare(`${prefix}-side`,'Loading',label+'Minimum side thrust',min.runwaySide,supplied>0?Math.max(supplied,min.runwaySide):1e-12,'force',`H_{runway}=\\max(s,${minimumSideShare})\\,\\max[${aistRule},\\,0.2(Q+T)]`,`Whole-crane minimum: AIST Table 3.2 ${force(min.aist.totalSide)}, ASCE 7 §4.9.4 ${force(min.asce.totalSide)}; governing ${force(min.totalSide)}. Runway share entered ${cd.sideShare}, adopted ${min.share}${cd.sideShare<minimumSideShare?` (shares below ${minimumSideShare} are not credited without a stiffness analysis of both runways)`:''}. Supplied runway pattern ${force(supplied)}. Table 3.2 η: mill/ladle/finished-product magnet 0.40, slab/scrap/clamshell/soaking/stripping 1.00, maintenance 0.30. Distribution: ${cd.distributionSource}. Design scales the supplied wheel side-force pattern up to the governing minimum; it never reduces supplied forces.`,['tr13-crane','asce']);
  }
  if(cd.drivenWheelLoad<=0){missing.push(`${c.name}: maximum load on driving wheels`);wait(`${prefix}-traction`,'Loading',label+'Minimum longitudinal traction','Enter the total maximum wheel load on this runway’s driving wheels.',['tr13-crane']);}
  else compare(`${prefix}-traction`,'Loading',label+'Minimum longitudinal traction',min.traction,Math.max(c.longitudinal,min.traction),'force','C_{ls}=\\max(C_{supplied},\\,0.20\\sum P_{driving,max},\\,0.10\\sum P_{wheel,max})',`AIST 20% of driving-wheel loads ${force(min.aist.traction)}; ASCE 7 §4.9.5 10% of this runway's maximum static wheel loads ${force(min.asce.longitudinal)}; supplied ${force(c.longitudinal)}. Design adopts ${force(Math.max(c.longitudinal,min.traction))}.`,['tr13-crane','asce']);
  if(!cd.bumperForce&&!cd.bumperBypassesGirder){missing.push(`${c.name}: bumper force or separate stop load path`);wait(`${prefix}-bumper`,'Loading',label+'Crane stop / bumper load','Enter the manufacturer bumper force at 100% travel speed, or confirm a defined stop load path that bypasses this girder. Stop/connection/frame capacities remain separate checks.',['tr13-crane']);}
  else if(cd.bumperBypassesGirder)checks.push(na(`${prefix}-bumper`,'Loading',label+'Crane stop / bumper load','User-defined stop force bypasses this girder; the separate stop load path must be designed.',['tr13-crane']));
  else compare(`${prefix}-bumper`,'Loading',label+'Crane stop / bumper load',1,1,'ratio','C_{bs}=F_{bumper,manufacturer}',`Manufacturer bumper ${format(cd.bumperForce,'force',p.units,3)} enters combinations 8/10 (LRFD) or 9/11 (ASD) as longitudinal girder force. This confirms input inclusion only; stop and connection capacities require their own load-path model.`,['tr13-crane']);
  if(cd.guideRollers)wait(`${prefix}-guides`,'Loading',label+'Guide roller forces','Guide roller wheel/contact forces and torsion distribution need a manufacturer-specific analysis.',['tr13-crane'],'unsupported');
  if(c.wheels.every(w=>w.lateral===0)&&min.runwaySide>0){missing.push(`${c.name}: missing lateral wheel-force pattern`);wait(`${prefix}-side-pattern`,'Loading',label+'Lateral wheel distribution','Provide the wheel side-force pattern to allocate the nonzero minimum runway side thrust.',['tr13-crane']);}
  if(p.reportPurpose!=='demonstration'&&/illustrative|example|fictitious|fictional|\bdemo\b/i.test(c.loadSource)){missing.push(`${c.name}: illustrative manufacturer schedule`);wait(`${prefix}-manufacturer`,'Loading',label+'Manufacturer schedule','Replace the illustrative wheel schedule and source with project manufacturer data before a design report can be generated.',['tr13-crane']);}
 });
 if(missing.length)wait('load-basis','Loading','AIST crane load combinations',`${nominalBasis} Combination results are provisional until these inputs are resolved: ${missing.join('; ')}.`,['tr13-load','dg7-errata']);
 else compare('load-basis','Loading','AIST crane load combinations',1,1,'ratio',p.method==='LRFD'?'1.2(D+C_{dm})+1.6(C_{vm}+C_{ss}+C_{ls})+L':'D+C_{dm}+C_{vm}+C_{ss}+C_{ls}+L',`${nominalBasis} Independent absent/empty/loaded crane states; Css, Cls, impact and bumper are single-crane actions.${di.concurrency==='full'?' Fully concurrent ASCE 7 combination C1 is also checked: every crane load as live load L, impact with side thrust and with every crane present.':''} Minimum lifted load zero. No impact in the combined lateral branch; impact enters the separate single-crane branch. Omitted environmental combinations reduce to displayed or dominated cases only under the confirmed runway scope.`,['tr13-load','dg7-errata']);
 const steps=p.cranes.length===1?40:p.cranes.length===2?12:6;
 let coarse=runwayDesignAnalysis(p,props,str,steps,20),fine=runwayDesignAnalysis(p,props,str,steps*2,20);
 const keys=['moment','shear','reaction','uplift','axial','lateralMoment','interaction','singleVertical','singleLateral','serviceReaction','fatigueMin','fatigueMax','wheelLoad','wheelNearEndLoad','torsion'] as const;
 const change=(a:DesignAnalysis,b:DesignAnalysis)=>Math.max(...keys.map(k=>Math.abs(a[k]-b[k])/Math.max(Math.abs(b[k]),1)));
 let travelSteps=steps*2;let convergence=change(coarse,fine);while(convergence>.01&&travelSteps<steps*(p.cranes.length===1?16:4)){coarse=fine;travelSteps*=2;fine=runwayDesignAnalysis(p,props,str,travelSteps,20);convergence=change(coarse,fine);}
 const spatial=runwayDesignAnalysis(p,props,str,travelSteps,40);
 // Track the actual refinement level when a third travel pass was required.
 let mesh=change(fine,spatial),a=spatial;
 if(mesh>.01){const finer=runwayDesignAnalysis(p,props,str,travelSteps,80);mesh=change(spatial,finer);a=finer;}
 a.convergence=convergence;a.meshConvergence=mesh;s.designAnalysis=a;
 compare('design-equilibrium','Analysis','Design response equilibrium',a.equilibriumError,1e-7,'ratio','\\epsilon_R\\le10^{-7}','Residual for each decomposed wheel and flange response.',['mechanics']);
 compare('design-travel','Analysis','Design combination refinement',convergence,.01,'ratio','\\epsilon_{travel}\\le0.01','Refinement includes interaction, single-crane serviceability, uplift and fatigue extrema.',['mechanics']);
 compare('design-mesh','Analysis','Design station refinement',mesh,.01,'ratio','\\epsilon_{mesh}\\le0.01','Exact wheel-position moments plus successively refined station and displacement grids.',['mechanics']);
 // DG7 vertical deflection by crane service class: L/600 for CMAA A to C, L/800 for D, L/1000 for E and F.
 const cmaaLimit=(k?:string)=>k==='E'||k==='F'?1000:k==='D'?800:0;
 const serviceClasses=[...p.cranes.map(c=>c.design?.cmaaClass),p.section.kind==='cap'?p.capDesign?.cmaaClass:undefined].filter((k):k is NonNullable<typeof k>=>!!k&&k!=='unconfirmed');
 const cmaaN=Math.max(0,...serviceClasses.map(cmaaLimit)),heaviest=serviceClasses.reduce((a,b)=>cmaaLimit(b)>cmaaLimit(a)?b:a,serviceClasses[0]??'');
 const nv=Math.max(p.verticalLimit,di.buildingClass==='A'||di.buildingClass==='B'?1000:600,cmaaN),nh=Math.max(400,p.lateralLimit);
 // Each bay against its own span; the governing bay is reported.
 const governingBay=(byBay:number[]|undefined,n:number,overall:number)=>{const values=byBay?.length===p.spans.length?byBay:undefined;if(!values)return {demand:overall,limit:shortest/n,bay:-1};const i=values.reduce((best,v,j)=>v*n/p.spans[j]>values[best]*n/p.spans[best]?j:best,0);return {demand:values[i],limit:p.spans[i]/n,bay:i};};
 const vb=governingBay(a.verticalByBay,nv,a.singleVertical),lb=governingBay(a.lateralByBay,nh,a.singleLateral),bayText=(g:{bay:number})=>g.bay<0?'Shortest bay limit.':`Governing bay ${g.bay+1} (L = ${format(p.spans[g.bay],'length',p.units,3)}); every bay is checked against its own span.`;
 compare('vertical','Serviceability','Vertical crane-load deflection',vb.demand,vb.limit,'length','\\delta_{v,single,static}\\le\\frac{L_{bay}}{\\max(n_{owner},n_{AIST},n_{CMAA})}',`AIST class ${di.buildingClass}: L/${di.buildingClass==='A'||di.buildingClass==='B'?1000:600}; ${serviceClasses.length?`CMAA ${heaviest}: L/${cmaaLimit(heaviest)||600} (DG7)`:'CMAA service class not entered: classes A to C, L/600 (DG7)'}; owner L/${p.verticalLimit}; governing adopted limit L/${nv}. One crane, no impact or girder dead load. ${bayText(vb)}`,['tr13-girder','criteria']);
 compare('lateral','Serviceability','Lateral bending deflection',lb.demand,lb.limit,'length','\\delta_{top,single}\\le\\frac{L_{bay}}{\\max(n_{owner},400)}',`Independent top-flange bending under the rail-head force couple, including vertical rail eccentricity. Rigid brace assumptions; Saint-Venant torsion/rail twist is checked separately. ${bayText(lb)}`,['tr13-girder','dg7','criteria']);
 compare('compact-flange','Strength','Compression flange compactness',str.flangeRatio,str.flangeLimit,'ratio','\\lambda_f=\\frac{b_f}{2t_f}\\le0.38\\sqrt{E/F_y}','AIST §5.8.2 requires compact elements. Cap branch checks W flange, free channel legs and unsupported cap-web outstands; bearing contact supports the overlapping web.',['tr13-girder','aisc-b']);
 compare('compact-web','Strength','Web compactness',str.webRatio,str.webLimit,'ratio','\\lambda_w=\\frac{h}{t_w}\\le3.76\\sqrt{E/F_y}',`Clear web depth ${format(str.h,'length',p.units,3)}. AISC catalogue kdes used for rolled shapes; no fillet credit for custom sections.`,['tr13-girder','aisc-b']);
 const validFlex=str.compact;
 if(!(di.netFlangeArea&&di.netFlangeArea>0))wait('flange-net','Strength','Tension flange holes / net-section rupture','Enter the least actual net area of either flange, deducting holes/stagger under B4.3. For unperforated flanges explicitly enter bf × tf. Both flanges can be in tension on a continuous runway. Viewer holes are representative and are not calculation input.',['aisc-f13'],'incomplete','F_uA_{fn}\\ge Y_tF_yA_{fg};\\quad M_n\\le(F_uA_{fn}/A_{fg})S_x');
 else if(!str.netLimitApplies)checks.push(na('flange-net','Strength','Tension flange holes / net-section rupture',`F13.1(a): Fu Afn ≥ Yt Fy Afg, Yt=${str.Yt}; least entered net area ${format(di.netFlangeArea,'area',p.units,3)}, gross flange area ${format(p.section.bf*p.section.tf,'area',p.units,3)}. This flange rupture limit does not apply; other flexural limit states remain.`,['aisc-f13']));
 else compare('flange-net','Strength','Tension flange holes / net-section rupture',a.moment,str.netMoment,'moment','M_{n,net}=\\frac{F_uA_{fn}}{A_{fg}}S_x',`F13.1(b), Yt=${str.Yt}. Least entered net area ${format(di.netFlangeArea,'area',p.units,3)} is conservatively applied over the whole runway and both tension flanges. This strength cap is also included in major-axis and concurrent interaction checks. Actual hole deductions require B4.3 verification.`,['aisc-f13'],a.governing.moment?.id);
 if(validFlex){
  if(p.section.kind==='cap'){
   // AISC F13.2: singly symmetric I-shaped members need 0.1 <= Iyc/Iy <= 0.9 for the compression flange.
   const capProps=cappedElasticProperties(p.section);
   if(capProps){const ratio=capProps.topI/props.Iy;compare('cap-proportion','Strength','Capped section · singly symmetric proportioning',Math.max(ratio/.9,.1/ratio),1,'ratio','0.1\\le I_{yc}/I_y\\le0.9',`AISC F13.2. I_yc/I_y = ${ratio.toFixed(3)} for the cap and W top flange in compression${p.system==='continuous'?`; ${(capProps.bottomI/props.Iy).toFixed(3)} for the W bottom flange`:''}.`,['aisc-f5']);
    if(p.system==='continuous'){const bottom=capProps.bottomI/props.Iy;compare('cap-proportion-bottom','Strength','Capped section · proportioning, bottom flange in compression',Math.max(bottom/.9,.1/bottom),1,'ratio','0.1\\le I_{yc}/I_y\\le0.9','AISC F13.2 for negative moment at the supports.',['aisc-f5']);}}
   compare('major','Strength',p.system==='continuous'?'Capped major flexure · both moment signs':'Capped major flexure · cap in compression',a.moment,p.system==='continuous'?Math.min(str.major,str.majorReverse??str.major):str.major,'moment',p.system==='continuous'?'M_n=\\min_{+,-}[R_{pg}F_{cr}S_{xc},F_yS_{xt}]':'M_n^+=\\min[R_{pg}F_{cr}S_{xc},F_yS_{xt}]',`${str.flexureBranch}. Lower beam/channel grade; F5 Lr (not DG7 Table A-2 F4 Lr). Compression flange rt includes one-third of compressed web. Governing Lp=${format(str.Lp,'length',p.units,3)}, Lr=${format(str.Lr,'length',p.units,3)}. No plastic reserve or moment-gradient increase.`,['aisc-f5','dg7-cap']);
   compare('minor','Strength','Capped top / bottom lateral flange flexure',Math.max(a.topLateralMoment/str.topMinor!,a.bottomLateralMoment/str.bottomMinor!),1,'ratio','U_f=\\max(|M_t|/M_{ct},|M_b|/M_{cb});\\quad M_{n,f}=F_yS_f','Each flange has its own elastic first-yield resistance; cap-channel rotated catalogue Ix contributes to the top flange. Concurrent H1 interaction also checks both flanges.',['dg7-cap','aisc-f6']);
  }else{
  compare('major','Strength','Major-axis flexure & lateral-torsional buckling',a.moment,str.major,'moment',`M_n=\\begin{cases}F_yZ_x&L_b\\le L_p\\\\ C_b[M_p-(M_p-0.7F_yS_x)\\frac{L_b-L_p}{L_r-L_p}]&L_p<L_b\\le L_r\\\\F_{cr}S_x&L_b>L_r\\end{cases}\\le M_p`,`${str.flexureBranch}; Cb=1.0, Lp=${format(str.Lp,'length',p.units,3)}, Lr=${format(str.Lr,'length',p.units,3)}, rts=${format(str.rts,'length',p.units,3)}. Available strength = ${p.method==='LRFD'?'0.90Mn':'Mn/1.67'}. ${str.netLimitApplies?'F13 net-flange strength cap applied. ':''}${p.section.kind==='welded'?'Conservatively J=0 in strength checks; approximate thin-plate J receives no favorable resistance credit. ':''}Required restraints must be verified separately.`,['aisc-f2','aisc-f13','dg7'],a.governing.moment?.id);
  compare('minor','Strength','Rail-head lateral flange flexure',a.lateralMoment,str.flangeMinor,'moment','H_t=H(1+a/h_0)+Pe/h_0,\\quad H_b=-Ha/h_0-Pe/h_0;\\quad M_{n,f}=F_yb_f^2t_f/4','DG7 force-couple model resolves loads at rail head to both flange centroids. Each flange is checked for its own lateral moment; the web receives no lateral resistance credit. Whole-section F6 resistance is not substituted for flange resistance.',['tr13-girder','aisc-f6','dg7'],a.governing.lateralMoment?.id);
  }
  if(di.axialLength>0&&di.torsionalLength>0&&di.bottomBraceSpacing>0){
   compare('axial','Strength','Longitudinal girder compression',a.axial,str.compression,'force','F_e=\\min(F_{ex},F_{ey},F_{ez});\\quad P_n=F_{cr}A_e',`E3 flexural / E4 torsional or monosymmetric flexural-torsional buckling; cap branch uses E4-3 and conservative E7 area reduction; effective axial area ${format(str.axialArea,'area',p.units,3)}. Axial load conservatively taken through the whole girder, including bumper where specified. Effective lengths require engineering support/restraint justification.`,['aisc-e','tr13-load'],a.governing.axial?.id);
   compare('combined','Strength','Concurrent axial & biaxial interaction',a.interaction,1,'ratio','U=\\begin{cases}P_r/P_c+\\frac89(B_1M_x/M_{cx}+B_1M_f/M_{cf})&P_r/P_c\\ge0.2\\\\ P_r/(2P_c)+B_1M_x/M_{cx}+B_1M_f/M_{cf}&P_r/P_c<0.2\\end{cases}\\le1',`H1-1 evaluated at coincident stations and crane states; maximum flange lateral moment controls. B1 uses conservative Cm=1 and alpha=${p.method==='LRFD'?1:1.6}; frame sidesway is outside this girder worksheet. Governing x=${format(a.governing.interaction?.location,'length',p.units,3)}.`,['aisc-h','dg7'],a.governing.interaction?.id);
  }else wait('combined','Strength','Concurrent axial & biaxial interaction','Enter axial effective length, torsional effective length and bottom-flange brace spacing. These are actual girder restraint inputs, independent of the illustrative 3D framing.',['aisc-e','aisc-h','dg7']);
 }else for(const [id,title] of [['major','Major-axis flexure & lateral-torsional buckling'],['minor','Rail-head lateral flange flexure'],['combined','Concurrent axial & biaxial interaction']])wait(id,'Strength',title,'AIST requires compact flanges and web. Select a compact girder or provide a separately verified section design.',['tr13-girder','aisc-f2'],'unsupported');
 compare('shear','Strength','Web shear · no tension field action',a.shear,str.shear,'force','V_n=0.6F_y d t_w C_{v1};\\quad C_{v1}=\\min(1,1.10\\sqrt{5.34E/F_y}/(h/t_w))',`G2.1 unstiffened web, no tension-field or intermediate-stiffener credit. Cv1=${str.Cv.toFixed(4)}; phi=${str.shearPhi}, Omega=${str.shearOmega}. Stocky rolled-web exception applied where valid.`,['tr13-girder','aisc-g'],a.governing.shear?.id);
 if(di.railDepth>0&&di.bearingLength>=str.k){
  const wheelBearing=2*(di.railDepth+p.section.tf),interior=concentratedResistance(p,str,wheelBearing,false),end=concentratedResistance(p,str,wheelBearing,true),support=concentratedResistance(p,str,di.bearingLength,true);
  const wheelNote=`AIST wheel bearing length 2(rail depth+tf)=${format(wheelBearing,'length',p.units,3)}. End-zone wheels are checked with reduced end resistance; overlapping wheel bearing lengths need a combined patch-load model.`;
  compare('wheel-yield','Local forces','Wheel web local yielding',Math.max(a.wheelLoad/interior.yielding,a.wheelNearEndLoad/end.yielding),1,'ratio','R_n=F_y t_w(5k+l_b);\\quad R_{n,end}=F_y t_w(2.5k+l_b)',wheelNote,['tr13-girder','aisc-j']);
  compare('wheel-cripple','Local forces','Wheel web crippling',Math.max(a.wheelLoad/interior.crippling,a.wheelNearEndLoad/end.crippling),1,'ratio','R_n=Ct_w^2[1+q(l_b/d)(t_w/t_f)^{1.5}]\\sqrt{EF_yt_f/t_w}',`${wheelNote} J10.4/5 end expression conservatively used for all wheels within d of an end; Qf=1.`,['aisc-j','tr13-girder']);
  compare('support-yield','Local forces','Support web local yielding',a.reaction,support.yielding,'force','R_{n,end}=F_y t_w(2.5k+l_b)','Worst reaction compared with unstiffened end resistance. No bearing-stiffener strength credit; shared support reactions include adjoining simple spans.',['aisc-j'],a.governing.reaction?.id);
  compare('support-cripple','Local forces','Support web crippling',a.reaction,support.crippling,'force','R_{n,end}=0.40t_w^2[1+q(l_b/d)(t_w/t_f)^{1.5}]\\sqrt{EF_yt_f/t_w}','Unstiffened end bearing conservatively controls all supports. Failing checks require a designed stiffener/seat; stored template geometry receives no capacity credit.',['aisc-j'],a.governing.reaction?.id);
  compare('web-compression','Local forces','Web compression buckling at wheel over support',Math.max(a.reaction,a.wheelLoad),support.compressionBuckling,'force','R_{n,end}=\\frac{12t_w^3\\sqrt{EF_y}}{h}','Conservative J10.5 end resistance for opposing compression at a wheel crossing a support. Worst wheel or support force used; no stiffener credit.',['aisc-j']);
  if(p.cranes.some(c=>c.wheels.some((w,i)=>i>0&&w.offset-c.wheels[i-1].offset<wheelBearing)))wait('wheel-patch','Local forces','Overlapping wheel bearing lengths','Adjacent effective wheel bearing patches overlap; grouped patch-load yielding/crippling must be evaluated separately.',['tr13-girder','aisc-j'],'unsupported');
 }else wait('local','Local forces','Wheel loads & concentrated support forces',`Enter actual rail depth and support bearing length (at least k=${format(str.k,'length',p.units,3)}). Viewer rail height and schematic seats do not establish the bearing geometry.`,['tr13-girder','aisc-j']);
 if(di.bottomBraceSpacing>0){const lb=Math.max(p.unbracedLength,di.bottomBraceSpacing),ratio=(str.h/p.section.tw)/(lb/p.section.bf);
  if(ratio>1.7)checks.push(na('sidesway','Local forces','Web sidesway buckling',`J10.4(b): (h/tw)/(Lb/bf)=${ratio.toFixed(3)}>1.7; this limit state does not apply under the unrestrained-flange rotation branch.`,['aisc-j']));
  else {const Cr=3.3e6,Rn=Cr*p.section.tw**3*p.section.tf/str.h**2*.4*ratio**3;compare('sidesway','Local forces','Web sidesway buckling',a.wheelLoad,available(Rn,p.method,.85,1.76),'force','R_n=\\frac{C_rt_w^3t_f}{h^2}0.4\\left(\\frac{h/t_w}{L_b/b_f}\\right)^3',`Unrestrained-flange rotation branch. Conservatively Cr=${format(3.3e6,'stress',p.units,3)} for all load positions. Largest unbraced length of either flange ${format(lb,'length',p.units,3)}.`,['aisc-j'],a.governing.moment?.id);}
 }else wait('sidesway','Local forces','Web sidesway buckling','Enter bottom-flange unbraced length; the largest unbraced length of either flange controls.',['aisc-j']);
 const minimum=di.environment==='exterior'?7.9375:6.35,thickness=p.section.kind==='rolled'?p.section.tf:Math.min(p.section.tf,p.section.tw);
 compare('minimum-thickness','Detailing','Minimum structural steel thickness',minimum,thickness,'length',p.units==='SI'?'t_{provided}\\ge\\begin{cases}7.9375\\,mm&exterior\\\\6.35\\,mm&interior\\end{cases}':'t_{provided}\\ge\\begin{cases}5/16\\,in&exterior\\\\1/4\\,in&interior\\end{cases}',`AIST §5.13 ${di.environment} construction. Rolled shapes controlled by mean flange thickness; welded girders by the thinner flange/web plate.`,['tr13-detail']);
 compare('rail-clips','Detailing','Opposing rail clip spacing',di.clipSpacing,di.railPad?609.6:762,'length',p.units==='SI'?'s_{clips}\\le\\begin{cases}609.6\\,mm&rail\\ pad\\\\762\\,mm&no\\ pad\\end{cases}':'s_{clips}\\le\\begin{cases}24\\,in&rail\\ pad\\\\30\\,in&no\\ pad\\end{cases}','Opposing pairs required. Clip capacity, lateral rail stiffness and thermal movement are separate from this maximum-spacing check. Viewer clips remain representative.',['tr13-detail']);
 if(di.fastener==='hook')compare('hook-bolts','Detailing','Hook bolt applicability',di.buildingClass==='A'||di.buildingClass==='B'||p.cranes.some(c=>(c.design?.ratedLoad??0)>177928.8646)?1:0,.5,'ratio',p.units==='SI'?'class\\notin\\{A,B\\},\\quad Q\\le177.929\\,kN':'class\\notin\\{A,B\\},\\quad Q\\le20\\,tons',`TR13 §5.16 excludes hook bolts for Class A/B or rated lifting forces over ${format(177928.8646,'force',p.units)}. Thermal movement and separate hook-bolt detailing remain required.`,['tr13-detail']);
 else checks.push(na('hook-bolts','Detailing','Hook bolt applicability','Rail clips selected; hook-bolt restriction does not apply.',['tr13-detail']));
 if(di.supportType==='bracket')compare('column-brackets','Detailing','Column bracket applicability · total reactions',a.serviceReaction,50*4448.221615,'force',p.units==='SI'?'R_{column,total}<222.411\\,kN':'R_{column,total}<50\\,kip','AIST §5.9.2 limit is a support-system suitability check, not bracket/column capacity. Includes girder dead load, all present loaded cranes and impact, conservatively on all cranes. Total reaction at a shared support is used.',['tr13-detail']);
 if(checks.find(c=>c.id==='column-brackets')?.utilization===1)checks.find(c=>c.id==='column-brackets')!.status='fail';
 if(di.supportType!=='bracket')checks.push(na('column-brackets','Detailing','Column bracket applicability · total reactions','Direct column bearing selected. The building/column design and its load path remain outside this girder worksheet.',['tr13-detail']));
 if(p.spans.some(span=>span>22860))wait('camber','Detailing','Long-span camber',`Spans over ${p.units==='US'?'75 ft':'22,860 mm'} require a camber profile for approximately dead-load plus half static live-load deflection. A single schematic camber value is insufficient for continuous/unequal bays.`,['tr13-girder'],'unsupported');
 else checks.push(na('camber','Detailing','Long-span camber',`No bay exceeds ${p.units==='US'?'75 ft':'22,860 mm'}; AIST §5.8.8 long-span camber rule does not apply.`,['tr13-girder']));
 if(p.spans.some(span=>span>15240))wait('long-span-backup','Bracing','Long-span backup / bottom-flange bracing',`Spans over ${p.units==='US'?'50 ft':'15,240 mm'} require a backup truss/plate and lower bracing, or a rational stiffness/torsion justification; bottom lacing carries at least 25% of top forces.`,['tr13-girder'],'unsupported');
 const F=fatigueResistance(p.fatigue.category,p.fatigue.cycles),range=a.fatigueMax-a.fatigueMin;
 if(p.fatigue.cycles<=20000&&!di.cycleSource.trim())wait('fatigue','Fatigue','Girder detail fatigue stress range','Enter the owner stress-fluctuation basis before excluding fatigue at 20,000 or fewer cycles.',['aisc-fatigue']);
 else if(p.fatigue.cycles<=20000)checks.push(na('fatigue','Fatigue','Girder detail fatigue stress range','AISC Appendix 3.1 requires fatigue evaluation above 20,000 applied stress fluctuations. Owner fatigue cycle basis still needs confirmation for this exclusion.',['aisc-fatigue','tr13-girder']));
 else if(!di.fatigueReference.trim()||!di.cycleSource.trim()||!p.fatigue.detail.trim()||/^(select|owner to confirm|replace)\b/i.test(p.fatigue.detail.trim()))wait('fatigue','Fatigue','Girder detail fatigue stress range',`Calculated provisional range ${format(range,'stress',p.units,3)} at ${di.fatiguePoint}, x=${format(p.fatigue.location,'length',p.units,3)}; category ${p.fatigue.category} FSR=${format(F.FSR,'stress',p.units,3)}. Enter the actual A-3.1 detail item, fabrication description and owner stress-fluctuation basis. Detailed checks add the warping and attachment stresses.`,['aisc-fatigue','tr13-load']);
 else compare('fatigue','Fatigue','Girder detail fatigue stress range',range,F.FSR,'stress','F_{SR}=\\max[F_{TH},6900(C_f/n_{SR})^{1/3}];\\quad\\Delta f=f_{max}-f_{min}',`Cds+Cvs+0.5Css, no impact/factors. ${p.cranes.length>1?di.fatigueCranes==='single'?'One crane at a time (TR-13 / DG7 single-crane basis). ':'Every arrangement of the cranes present. ':''}Empty, loaded, absent and reversed lateral cases at the selected flange edge; conservative constant-amplitude envelope. Cf=${F.Cf}, FTH=${format(F.Fth,'stress',p.units,3)}, category ${p.fatigue.category}; detail ${di.fatigueReference}: ${p.fatigue.detail}. Cycles are stress fluctuations, not crane traversals: ${di.cycleSource}. Owner must account for all wheel-induced fluctuations and variable-amplitude damage. This checks one selected detail; local weld/connection fatigue is separate.`,['aisc-fatigue','tr13-load']);
 const verticalSign=di.fatiguePoint.startsWith('top')?-1:1,edgeSign=di.fatiguePoint.endsWith('left')?-1:1;
 const verticalSystem=beamSystem(p.spans,p.section.E*props.Ix,p.system),deadQ=p.deadLoad+p.railWeight+props.weight;
 const deadResponse=verticalSystem.evaluate([],deadQ),md=momentAt(p.fatigue.location,deadResponse.reactions,[],deadQ);
 const liveResponse=verticalSystem.evaluate([],di.liveLoad),ml=momentAt(p.fatigue.location,liveResponse.reactions,[],di.liveLoad);
 const flangeI=p.section.tf*p.section.bf**3/12,railQ=-verticalSign*p.railWeight*p.railEccentricity/props.h0;
 const flangeSystem=beamSystem(p.spans,p.section.E*flangeI,p.system,verticalSign<0?p.lateralBraceSpacing:di.bottomBraceSpacing||L);
 const railResponse=flangeSystem.evaluate([],railQ),railM=momentAt(p.fatigue.location,railResponse.reactions,[],railQ);
 const mean=verticalSign*md/props.Sx+edgeSign*railM/(flangeI/(p.section.bf/2));
 const peak=Math.max(...[0,verticalSign*ml/props.Sx].flatMap(extra=>[Math.abs(mean+extra+a.fatigueMin),Math.abs(mean+extra+a.fatigueMax)]));
 compare('fatigue-peak','Fatigue','Peak elastic cyclic stress',peak,.66*p.section.Fy,'stress','|f_{peak}|\\le0.66F_y','Appendix 3.1 elastic peak limit at the same flange edge; includes dead-load major bending, eccentric rail dead-load flange bending and possible occupancy live load. Warping stress is not included and needs the separate torsion check.',['aisc-fatigue']);
 // A force couple captures flange bending but does not establish the complete
 // Saint-Venant/warping, twist, load-height stability or brace system solution.
 if(a.wheelLoad>1||a.torsion>1||Math.abs(p.railEccentricity)>1e-6||p.railHeight>0)wait('torsion','Strength','Rail torsion, warping & load-height stability',`Factored wheel torque up to ${format(a.torsion,'moment',p.units,3)}. The flange force-couple checks are implemented, but Saint-Venant/warping stress, twist and the effect of above-centroid loading on stability need a restraint-dependent torsion model. AIST §5.8.1 explicitly places the general solution beyond this report’s scope.`,['tr13-girder','dg7'],'unsupported','T=P e+H(a+h_0/2)');
 else checks.push(na('torsion','Strength','Rail torsion, warping & load-height stability','No modeled eccentric wheel torque; validate the actual rail/load eccentricities and all torsional restraints.',['tr13-girder','dg7']));
 const Cd=p.system==='continuous'?2:1,braceForce=.02*a.moment*Cd/props.h0,braceStiffness=(p.method==='LRFD'?1/.75:2)*10*a.moment*Cd/(Math.min(p.lateralBraceSpacing,di.bottomBraceSpacing||L)*props.h0);
 wait('brace','Bracing','Stability brace strength & stiffness',`Point-brace flexure-only minimum strength ${format(braceForce,'force',p.units,3)} and stiffness ${format(braceStiffness,'stiffness',p.units,3)} (A-6-7/8). Cd=${Cd}, conservative for continuous double curvature. Actual bracing includes concurrent side thrust, axial stability contributions, connection flexibility and both flange restraints. Brace geometry alone does not establish system capacity.`,['aisc-brace','tr13-girder'],'incomplete','P_{br}=0.02M_r C_d/h_0,\\quad\\beta_{br}=\\frac{10M_r C_d}{\\phi L_{br}h_0}');
 if(a.uplift>1)wait('hold-down','Connections','Support uplift / hold-down load path',`Factored uplift ${a.uplift.toFixed(0)} N. The linear support model assumes a bilateral restraint. Design actual hold-downs, bearing/plate load path and cyclic bolt/weld effects; gravity bearing alone cannot provide this reaction.`,['aisc-j','tr13-girder']);
 if(p.connections.enabled){
  compare('bolt-spacing','Connections','Bolt pitch · geometric minimum',8/3*p.connections.boltDiameter,p.connections.boltPitch,'length','s\\ge(8/3)d_b','AISC J3.3 minimum bolt center spacing. This geometric check does not verify the connection force path or fatigue detail.',['aisc-j']);
  const weldN=.6*p.connections.Fexx*.70710678*p.connections.weldSize*p.connections.weldLength;
  compare('weld-screen','Connections','Single weld line · direct shear screening',a.reaction,available(weldN,p.method,.75,2),'force','R_n=0.60F_{EXX}(0.707wL)','J2.4 weld-metal resistance of one entered effective weld line. No directional increase or extra weld lines credited. Weld group eccentricity, connected metal, fatigue and fit-up require the connection model.',['aisc-j']);
  wait('connection-end','Connections','Girder bearing / end connection','Define the bearing seat, end rotation release, bolt grade/pretension, slip surfaces, hole types, bolt group and plate dimensions. Bolt shear/tension, slip, bearing, block shear, net section, plate flexure and eccentric weld groups require the actual connection geometry. The 3D bolts are representative.',['aisc-j','tr13-detail']);
  wait('connection-stiffener','Connections','Bearing stiffeners & welds','Unstiffened web checks are calculated. If a bearing stiffener is needed, its fit, effective web strip, compression buckling and continuous weld load path must be designed under J10.8 and AIST §5.8.5; no template strength credit is taken.',['aisc-j','tr13-girder']);
  wait('connection-restraint','Connections','Top-flange tieback / longitudinal connections','Provide the actual side-thrust and longitudinal load paths, cyclic slip-critical bolt details and connection fatigue calculations. Stored geometry and representative 3D hardware do not establish capacities.',['aisc-j','tr13-detail']);
 }else wait('connections-scope','Connections','Girder connection and support design','Design scope requires girder connections and load paths. Enable connection inputs and complete their actual engineering models; disabling templates does not waive these checks.',['tr13-girder']);
 // Stated in every design report so local bracket/seat/web checks are never read as building adequacy.
 checks.push(pending('supporting-structure','Supporting structure',p.existingColumn?.enabled&&p.existingColumn.isNew?'Bracing connections and seismic design':p.existingColumn?.enabled?'Existing frame, connections & foundations beyond the checked column':'Existing columns, frame, bracing & foundations',`Not checked by this calculation. ${p.existingColumn?.enabled&&p.existingColumn.isNew?`The new column member is checked under New column${p.columnBase?.enabled?', and its base plate, anchor rods and footing under New column base':''}; the column-side connections of the ties`:p.existingColumn?.enabled?'The existing column member is checked under Existing column for the most heavily loaded support; the column-side connections of brackets and ties':di.supportType==='bracket'?'The receiving columns and the column-side connections of brackets and ties':'The supporting columns'}, the building frame, ${p.longitudinalBracing?.enabled?'the collector and connections of the crane-level bracing (its diagonals are checked under Longitudinal bracing), crane stops':'crane-level longitudinal bracing and stops'}${p.existingColumn?.isNew&&p.columnBase?.enabled?p.existingColumn.seismic?.enabled?', the crane-level bracing for seismic forces along the runway':', seismic design of the freestanding runway structure':', anchors and foundations'} must be verified by the engineer of record for the reported support reactions (vertical including impact, lateral and longitudinal) combined with the building's dead, live, roof, snow, wind and seismic loads under the governing ASCE 7 combinations. Local bracket, seat and web checks reported here do not establish member, frame or foundation capacity.`,['asce','tr13-bracket'],'excluded'));
 return checks;
}
