import type { ReferenceRecord } from './types';
export const referenceVersion='2026-10-09.angle-ties-1';
const aiscUrl='https://f.openpdfs.org/zydD8bRnd14.pdf';
const trUrl='https://www.aist.org/AIST/aist/AIST/Technology_Committees/Cranes/00-TR1319-EDITED-02242020.docx';
const steel=(id:string,clause:string,evidence:string):ReferenceRecord=>({id,title:'ANSI/AISC 360-16',edition:'2016 · June 2018 printing',clause,url:aiscUrl,status:'verified',evidence:'Original AISC-authored specification read from a public PDF mirror; publisher and printing checked. '+evidence+' Hash and retrieval provenance in references/SOURCE_REGISTER.md. Verified text does not certify project applicability or restraints.'});
const aist=(id:string,clause:string,evidence:string):ReferenceRecord=>({id,title:'AIST Technical Report 13',edition:'Supplied reference · February 24, 2020',clause,url:trUrl,status:'verified',evidence:'User-supplied reference read and rendered. '+evidence+' Exact source-file identity, date, hash and clause locations are recorded in references/SOURCE_REGISTER.md.'});
export const references:ReferenceRecord[] = [
 {id:'angle-tie-basis',title:'Custom angle tiebacks / AISC section geometry',edition:'AISC Shapes Database v16.0; custom arrangement 2026-10-09',clause:'US L-section dimensions; DG7 §11.2 movement principles',url:'https://www.aisc.org/aisc/publications/steel-construction-manual/aisc-shapes-database-v160/',status:'partial',evidence:'Single and paired L-section ties use catalogue d, b and t from the pinned AISC workbook. The selectable top-flange slotted column-angle arrangement is inspired by the user-supplied Figure 14, whose publication is not identified; paired clips and the cap attachment are application adaptations. The earlier welded gusset arrangement is retained. Neither is a prequalified AISC detail. DG7 and Fisher / Van de Pas establish lateral restraint, imposed movement and fatigue requirements, not approval of these angles or their both-flange placement. Strength, buckling, eccentricity, load sharing, welds, stiffness and movement remain unverified; no flat-bar capacity is inherited.'},
 {id:'existing-bracket-basis',title:'Existing bracket installation / assessment basis',edition:'Great Falls Airport RFP · August 2025; app mechanics 2026-10-09',clause:'RFP pp. 1–3; AISC J3/J4; elastic seat-strip mechanics',url:'https://flygtf.com/wp-content/uploads/2025/09/RFPbridgecrane082925.pdf#page=3',status:'partial',evidence:'The RFP specifies new runway beams bolted to existing PEMB brackets. The photograph establishes an arrangement only, with no verified bracket dimensions, material, weld or capacity. The app checks the new seat plate and bolt fit, collects simultaneous eccentric support actions, and compares them with documented available resistance/fatigue envelopes. Existing assembly strength, contact, serviceability and new attachment adequacy require a project engineering assessment. No RFP or catalogue rating is assigned.'},
 {id:'connection-options',title:'Runway connection arrangement library',edition:'2026-10-09',clause:'Support and tieback families; applicability gates',url:'',status:'partial',evidence:'TR13 §5.9.2 recognizes column brackets and requires eccentricity, rotation and fatigue review. Haunched seats and rolled corbels are editable concepts within that family, not source-prescribed details. Rectangular twin-rib brackets and paired-flat-bar ties have component checks. Existing AISC W-section and custom built-up I-brackets retain separate geometry and assessment inputs. The RFP-style W section is user-selected, not specified by the source. Both existing types use new-seat checks and documented available resistances from an external assessment; existing steel strength is not calculated. Other alternative families block report generation; no current-model or proprietary capacities are inherited.'},
 {id:'tieback-practice',title:'Fisher & Van de Pas · Crane runway fatigue',edition:'Engineering Journal · 2002',clause:'Printed p.68 / Fig.1; DG7 §11.2 and §14.5',url:'https://ej.aisc.org/index.php/engj/article/view/777',status:'verified',evidence:'Published discussion requires lateral restraint and girder-end / column-shortening movement compatibility. Direct flange attachment is preferred. The flexible-plate preview is an original generic concept, not a dimensioned reproduction or proof of fatigue suitability.'},
 {id:'bearing-link-practice',title:'Manufacturer articulated tieback families',edition:'Gantrex / Molyneux · accessed 2026-10-08',clause:'Single and double tiebacks; bearing link ends',url:'https://www.gantrex.com/products/tieback-assemblies/',status:'verified',evidence:'Gantrex describes single links and double adjacent-girder links to a shared column attachment. Molyneux describes PFSL / TBL bearing-link families at https://www.molyneuxindustries.com/TieBacks.html. The generic model uses no supplier dimensions, certification, stiffness or resistance ratings. Assembly, fatigue and movement design require the selected supplier package.'},
 {id:'flange-saddle-mechanics',title:'Custom flange-saddle mechanics',edition:'Elastic component model · 2026-10-08',clause:'Section modulus; simply supported strips; elastic weld groups; component flexibility',url:'',status:'partial',evidence:'Custom idealization, not a published or prequalified connection. Saddle strips span between edge welds; actual saddle length alone is credited as girder-flange strip width. No composite saddle/flange contribution. Local flexibility is added in series. Full reversed local range is combined with global girder fatigue. Independent algebra and deficient-component regression tests check implementation. DG7 §11.2 requires movement-compatible tiebacks; end rotation, thermal travel, column shortening, global frame interaction and fabrication access remain unverified.'},
 aist('tr13-bracket','§5.9.2; Commentary 5.9.2','Bracket reaction recommendation below 50 kip; impact in bracket and column attachment; support rotation, eccentricity and fatigue considerations.'),
 steel('bracket-basis','F11; G4; J2; J4; J10.1–J10.4; J10.6; Appendix 3','Welded twin rectangular-rib bracket. Conservative elastic load path; no composite seat contribution. F11 with doubled cantilever length and Cb=1. TR13 §5.9.2 and Commentary require impact, rotation/eccentricity and recommend reactions below 50 kip. Receiving column global/frame design remains separate.'),
 steel('aisc-f5','F4 User Note; F4.2 rt definition; F5-1–F5-10; E4-3; F13.3','Conservative capped-I flexure for both compression flanges, F5 Lp/Lr and Rpg, tension yielding, singly symmetric compression and full cap-force development.'),
 {id:'dg7-cap',title:'AISC Design Guide 7 · Capped runway girders',edition:'Third edition · 2019',clause:'§13.3; §14.1; Examples 14.1.3/14.1.4; Tables A-1/A-2',url:'https://cloud.aisc.org/ecom/DG/D807-19W-dxe.pdf',status:'verified',evidence:'Supplied original read: full bearing/contact concerns; continuous weld recommendation; E/F exclusion; cap force couple; F5 use via F4 User Note; VQ/I weld shear flow and fatigue. App conservatively uses F5 Lr rather than the example’s F4 table Lr, elastic lateral resistance and both bending signs.'},
 {id:'cap-sectorial',title:'Design of Crane Runway Beam with Channel Cap',edition:'Ellifritt & Lue · AISC Engineering Journal · 1998',clause:'Eqs.1–6; open-section sectorial integration',url:'https://ej.aisc.org/index.php/engj/article/view/699',status:'verified',evidence:'Original publisher PDF and equations visually read. Median-line sectorial integration with merged contacting top plates, zero-area offsets, no fillet credit and J=sum of component J without overlap credit. Verified against unequal-I closed forms, coordinate invariance and constant-moment monosymmetric eigenvalues; empirical fitted equations are not design inputs.'},
 {id:'cap-channel-study',title:'Design of Crane Runway Beam with Channel Cap',edition:'Ellifritt & Lue · AISC Engineering Journal 35(2) · 1998',clause:'Eqs.11, 12 and 15; pp.41–49',url:'https://ej.aisc.org/index.php/engj/article/view/699',status:'partial',evidence:'Original publisher PDF visually checked. Approximate Cw/J/monosymmetry estimates shown separately for research; area ratio 0.20–0.95 and CMAA A–C scope. Repeated Eq.18 defines R inconsistently with Eq.11. No capped resistance, torsional stress recovery or weld adequacy is enabled by these estimates. Hash and limitations in references/SOURCE_REGISTER.md.'},
 {id:'vlasov',title:'Torsional Analysis of Steel Sections',edition:'Moore & Mueller · AISC Engineering Journal · 2002',clause:'pp.182–188; torsional stress equations and pinned/fixed-end solutions',url:'https://ej.aisc.org/index.php/engj/article/download/789/788',status:'verified',evidence:'Publisher PDF retained and equations checked against independent hyperbolic solutions in lateralTorsion.test.ts. Thin-walled open I-section mechanics; supporting building is excluded.'},
 {id:'ltb-energy',title:'Lateral-Torsional Buckling · Energy-Based Formulations',edition:'Nayak, Anilkumar & Subramanian · AISC Engineering Journal · 2024',clause:'Eq.6; constant-moment pinned-end analytical benchmark',url:'https://ej.aisc.org/index.php/engj/article/download/1328/1321/1342',status:'verified',evidence:'Publisher PDF retained. Elastic lateral/warping coupling tested against the analytical critical moment. The vertical-load-height term is derived from load potential; this mechanics reference does not change the AISC 360-16 design edition.'},
 steel('aisc-h3','H3.3 · H3-7, H3-8, H3-9','Non-HSS normal/shear yielding and analysis-based elastic buckling; separate F2/H1 checks remain.'),
 steel('aisc-connections','J2.2, J2.4; J3.1–J3.10; J4.1–J4.5; J7; J10.8','Bolt-group forces, standard-hole pretension/slip, combined bolt shear/tension, plate bearing/net section/block shear, elastic weld groups, fitted bearing stiffeners.'),
 {id:'mechanics',title:'Euler–Bernoulli beam mechanics',edition:'Linear elastic analysis',clause:'Direct stiffness; equilibrium; superposition',url:'',status:'verified',evidence:'Independent closed-form point-load/UDL, continuous-span compatibility, equilibrium and moving-load refinement benchmarks. Mechanics basis, not a crane standard.'},
 {id:'criteria',title:'Project serviceability criteria',edition:'User-defined',clause:'Stricter owner span/deflection ratios',url:'',status:'verified',evidence:'Owner criteria supplement AIST limits in design scope. Analysis scope compares supplied criteria without asserting code compliance.'},
 aist('tr13','§§3.6, 3.10, 5.7–5.9, 5.13–5.17','Crane/runway provisions and limitations inspected.'),
 aist('tr13-class','§1.4 · Table 1.1 · building classes A–D','Building repetitions differ from CMAA crane classes.'),
 aist('tr13-crane','§3.6.2 · Table 3.2; §3.6.3','Impact, greatest-of side thrust, driving-wheel traction and manufacturer full-speed bumper.'),
 aist('tr13-load','§§3.10.1, 3.10.2.1–3.10.2.4','Dead/lift/impact separation, single/multiple crane LRFD/ASD cases and unfactored fatigue. Runway-only projection is explicit.'),
 aist('tr13-girder','§§5.7, 5.8.1–5.8.9','Compactness; wheel bearing length; single-crane deflection; no tension field action; force-couple and long-span requirements. General torsion solution is beyond TR13.'),
 aist('tr13-detail','§5.9.2; §§5.13–5.16.4','Bracket support below 50 kip, minimum thickness, cyclic slip-critical bolts, paired rail clips and pad spacing.'),
 steel('aisc-b','B4.1 · Tables B4.1a/b','Compactness and clear web depth.'),
 steel('aisc-e','E3, E4, E7 · Appendix 8.2','Axial buckling, effective plate widths, conservative B1 amplification.'),
 steel('aisc-f2','F1/F2 · F2-1–F2-8','Compact doubly symmetric I-section yielding/LTB; phi=0.90, Omega=1.67, Cb=1.0. Cap/noncompact girders remain outside implemented branch.'),
 steel('aisc-f6','F6 · F6-1–F6-4','Minor-axis strength; DG7 flange-only rail force-couple resistance.'),
 steel('aisc-f13','F13.1 · F13-1; B4.3','Tension flange net-section rupture; actual minimum net flange area across both flanges, not illustrative viewer holes.'),
 steel('aisc-g','G2.1 · G2-1–G2-5','Unstiffened-web shear, no tension field action; stocky rolled-web factors.'),
 steel('aisc-j','J2.4, J3.3, J10.2–J10.8','Weld direct shear, bolt pitch and web yielding/crippling/sidesway/compression buckling. Complete connections still require actual engineering models.'),
 steel('aisc-h','H1.1 · H1-1a/b','Concurrent axial/biaxial interaction, with restraint and second-order assumptions recorded.'),
 steel('aisc-fatigue','Appendix 3.1–3.3 · A-3-1M; Table A-3.1','Constants/thresholds A, B, B′, C, D, E, E′; elastic peak limit, reversal and detail applicability. Selected girder detail; detailed package adds signed warping/local ranges, duty bins, conservative all-cycle bounds, Category F throats and C-double-prime roots.'),
 steel('aisc-brace','Appendix 6.3.1b · A-6-7/8','Point-brace requirements; detailed template includes concurrent lateral/axial demands and member/gusset/bolt/weld stiffness in series. Building interfaces remain fixed.'),
 {id:'asce',title:'ASCE/SEI 7-16',edition:'2016',clause:'Chapter 2 / §4.9 · building actions outside runway projection',url:'https://amplify.asce.org/content/standard/9780784414248/part/provisions/standard-chapter/s4',status:'partial',evidence:'DG7 reproduces crane provisions. App references AIST Technical Report 13; it does not validate roof/wind/seismic building design or all ASCE provisions.'},
 {id:'dg7',title:'AISC Design Guide 7 · Industrial Building Design',edition:'Third edition · 2019',clause:'Chapters 11–14; §14.1; Examples 14.1.1/14.1.2',url:'https://cloud.aisc.org/ecom/DG/D807-19W-dxe.pdf',status:'verified',evidence:'User-supplied PDF cover confirms third edition despite incorrect second-edition metadata. Relevant chapters read. Rail-head flange force couple and AISC interaction recommendation used; W24×131 examples provide benchmarks.'},
 {id:'dg7-errata',title:'DG7 revisions and errata',edition:'February 16, 2023',clause:'Pages 55, 56 and 70; appended to supplied PDF',url:'https://www.aisc.org/media/s0hpvjsn/dg-07_2023_revisions-and-errata-list_print-and-dig_feb-2023.pdf',status:'verified',evidence:'Supplied PDF final page checked: LRFD 2b uses 1.6(Cvm+Css+Cls), 2c uses Ci, cap-channel example uses A572 Grade50. Supplied AIST Technical Report 13 reference already includes corrected terms.'}
];
export const ref=(id:string)=>references.find(r=>r.id===id)!;
