import { columnBaseSchema } from './columnBaseInputs';
import { z } from 'zod';
import { runwayDetailsSchema, type RunwayDetailResults } from './runwayDetails';
import { capDesignSchema } from './capDesignInputs';
import { existingColumnSchema } from './existingColumnInputs';
import { longitudinalBracingSchema } from './longitudinalBracingInputs';
import type { LongitudinalBracingResult } from './longitudinalBracing';
import type { SupportReactionSet } from './supportReactions';
import type { ExistingColumnResult } from './existingColumn';
export const maxRunwayBays = 6;
const positive = z.number().finite().positive();
const nonnegative = z.number().finite().nonnegative();
export const craneDesignSchema=z.object({control:z.enum(['cab','pendant']),type:z.enum(['mill','magnet','maintenance','stacker']),ratedLoad:nonnegative,trolleyWeight:nonnegative,bridgeWeight:nonnegative,rigidArmWeight:nonnegative,drivenWheelLoad:nonnegative,sideShare:nonnegative.max(1),distributionSource:z.string().max(500),splitConfirmed:z.boolean(),bumperForce:nonnegative,bumperBypassesGirder:z.boolean(),guideRollers:z.boolean(),
 /** CMAA 70/74 crane service class from the crane supplier; D, E and F tighten the vertical deflection limit (DG7). */
 cmaaClass:z.enum(['unconfirmed','A','B','C','D','E','F']).optional()});
export const aistSchema=z.object({buildingClass:z.enum(['A','B','C','D']),classConfirmed:z.boolean(),buildingCycles:nonnegative,environment:z.enum(['interior','exterior']),railDepth:nonnegative,bearingLength:nonnegative,netFlangeArea:nonnegative.optional(),bottomBraceSpacing:nonnegative,axialLength:nonnegative,torsionalLength:nonnegative,liveLoad:nonnegative,runwayOnly:z.boolean(),supportType:z.enum(['bracket','column']),clipSpacing:positive,railPad:z.boolean(),fastener:z.enum(['clips','hook']),camber:nonnegative,fatigueCranes:z.enum(['all','single']).optional(),concurrency:z.enum(['tr13','full']).optional(),fatiguePoint:z.enum(['top-left','top-right','bottom-left','bottom-right']),fatigueReference:z.string().max(500),cycleSource:z.string().max(500)});
export const sectionSchema = z.object({ kind:z.enum(['welded','rolled','cap']), name:z.string().max(100), d:positive, bf:positive, tf:positive, tw:positive, capWidth:positive, capDepth:positive, capTf:positive, capTw:positive, Fy:positive, Fu:positive, E:positive, density:positive, Ix:positive, Iy:positive, A:positive, Sx:positive, Sy:positive, Zx:positive, Zy:positive, J:positive, Cw:positive, propertySource:z.string().max(500), catalogueId:z.string().max(30).optional(), capCatalogueId:z.string().max(30).optional() });
export const craneSchema = z.object({ id:z.string().max(100), name:z.string().min(1).max(100), wheels:z.array(z.object({ offset:nonnegative, loaded:positive, unloaded:nonnegative, lateral:nonnegative })).min(2).max(16), impact:nonnegative.max(1), includesImpact:z.boolean(), longitudinal:nonnegative, minSeparation:nonnegative, travelStart:z.number().finite(), travelEnd:positive, operatingClass:z.string().min(1).max(100), loadSource:z.string().max(500),design:craneDesignSchema.optional() });
export const projectSchema = z.object({ schemaVersion:z.literal(1), reportPurpose:z.enum(['project','demonstration']).optional(), reportFormat:z.enum(['compact','detailed']).optional(), drawing:z.object({originator:z.string().max(100),checker:z.string().max(100),datumElevation:z.number().finite(),datumLabel:z.string().min(1).max(80),railElevation:z.number().finite().positive().optional(),eor:z.object({name:z.string().max(100),firm:z.string().max(100),license:z.string().max(60),jurisdiction:z.string().max(60)}).optional(),issue:z.enum(['preliminary','permit','construction']).optional(),code:z.object({building:z.string().max(160),editions:z.enum(['2016','2022']),reviewed:z.boolean()}).optional(),revisions:z.array(z.object({rev:z.string().max(4),date:z.string().max(20),description:z.string().max(120),by:z.string().max(12)})).max(6).optional()}).optional(), details:runwayDetailsSchema.optional(), capDesign:capDesignSchema.optional(), existingColumn:existingColumnSchema.optional(), columnBase:columnBaseSchema.optional(), longitudinalBracing:longitudinalBracingSchema.optional(), title:z.string().min(1).max(120), number:z.string().max(80), engineer:z.string().max(100), units:z.enum(['US','SI']), method:z.enum(['LRFD','ASD']), scope:z.enum(['design','analysis']), system:z.enum(['simple','continuous']), spans:z.array(positive.max(100000)).min(1).max(maxRunwayBays), continuation:z.object({left:nonnegative.max(100000),right:nonnegative.max(100000),source:z.string().max(300)}).optional(), section:sectionSchema, cranes:z.array(craneSchema).min(1).max(3), deadLoad:nonnegative, railWeight:nonnegative, railEccentricity:z.number().finite(), railHeight:nonnegative, unbracedLength:positive, lateralBraceSpacing:positive, verticalLimit:positive, lateralLimit:positive, criteriaSource:z.string().min(1).max(500), fatigue:z.object({ category:z.enum(['A','B','B1','C','D','E','E1']), cycles:positive, detail:z.string().max(500), location:nonnegative }), connections:z.object({ enabled:z.boolean(), bolts:z.number().int().min(1).max(100), boltDiameter:positive, plateThickness:positive, edgeDistance:positive, boltPitch:positive, weldSize:positive, weldLength:positive, stiffenerThickness:positive, stiffenerWidth:positive, braceArea:positive, braceLength:positive, braceRadius:positive, Fexx:positive }), aist:aistSchema.optional(),notes:z.string().max(5000) });
export type ProjectInput = z.infer<typeof projectSchema>;
export type Section = ProjectInput['section'];
export type Crane = ProjectInput['cranes'][number];
// 'excluded': required but outside this calculation (shown as BY OTHERS); never a pass, does not block export.
export type Status = 'pass'|'fail'|'not-applicable'|'incomplete'|'unsupported'|'unverified'|'excluded';
export interface ReferenceRecord { id:string; title:string; edition:string; clause:string; url:string; status:'verified'|'partial'|'unverified'; evidence:string; }
export interface CheckResult { id:string; group:string; title:string; status:Status; demand?:number; capacity?:number; utilization?:number; quantity?:'length'|'force'|'moment'|'stress'|'ratio'|'stiffness'|'pressure'; equation:string; substitution?:string; referenceIds:string[]; note:string; caseId?:string; }
export interface Properties { A:number; Ix:number; Iy:number; Sx:number; Sy:number; Zx:number; Zy:number; J:number; Cw:number; cy:number; h0:number; weight:number; }
export interface PointLoad { x:number; vertical:number; lateral:number; crane:string; }
export interface LoadCase { id:string; positions:number[]; points:PointLoad[]; lateralSign:number; }
export interface EnvelopePoint { x:number; momentMax:number; momentMin:number; lateralMax:number; lateralMin:number; shearMax:number; shearMin:number; deflectionMax:number; deflectionMin:number; lateralDeflectionMax:number; lateralDeflectionMin:number; }
export interface Demand { moment:number; lateralMoment:number; shear:number; reaction:number; uplift:number; deflection:number; lateralDeflection:number; stressRange:number; longitudinal:number; governing:Record<string,LoadCase>; reactions:number[]; }
export interface Analysis { envelope:EnvelopePoint[]; demand:Demand; cases:number; convergence:number; meshConvergence:number; equilibriumError:number; deadMoment:number; selfWeight:number; }
export interface DesignCaseSummary { id:string; equation:string; moment:number; lateralMoment:number; shear:number; reaction:number; axial:number; interaction:number; positions:number[]; location:number; }
export interface DesignAnalysis { combinations:DesignCaseSummary[]; cases:number; convergence:number; meshConvergence:number; equilibriumError:number; singleVertical:number; verticalByBay?:number[]; lateralByBay?:number[]; serviceRotation?:number; deadRotation?:number; singleLateral:number; endRotation:number; serviceReaction:number; fatigueMin:number; fatigueMax:number; wheelLoad:number; wheelNearEndLoad:number; torsion:number; moment:number; shear:number; reaction:number; uplift:number; axial:number; lateralMoment:number; topLateralMoment:number; bottomLateralMoment:number; interaction:number; governing:Record<string,DesignCaseSummary>; }
export interface CalculationSnapshot { revision:string; createdAt:string; input:ProjectInput; errors:string[]; warnings:string[]; properties:Properties|null; analysis:Analysis|null; checks:CheckResult[]; designAnalysis?:DesignAnalysis; detailResults?:RunwayDetailResults; supportReactions?:SupportReactionSet; existingColumn?:ExistingColumnResult; columnBase?:import('./columnBase').ColumnBaseResult; longitudinalBracing?:LongitudinalBracingResult; bracingSystem?:import('./newColumnBracing').BracingSystemResult; eligible:boolean; referenceVersion:string; }
