import type { ReactNode } from 'react';
import {format,type Quantity} from '../engine/units';
import { emptyAistInputs, emptyCraneDesign, type AistInputs as Inputs, type CraneDesign } from '../engine/aistLoads';
import type { Crane, ProjectInput } from '../engine/types';
type NumericField=(label:string,value:number,onChange:(n:number)=>void,q?:Quantity,help?:string,min?:number)=>ReactNode;
const Text=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label className="field"><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)}/></label>;
export function AistInputs({input,onChange,numeric,units='US'}:{input?:Inputs;onChange:(patch:Partial<Inputs>)=>void;numeric:NumericField;units?:ProjectInput['units']}){
 const d=input??emptyAistInputs,field=(label:string,key:keyof Inputs,q:Quantity='length',help?:string)=>numeric(label,(d[key]??0) as number,v=>onChange({[key]:v}),q,help);
 return <div className="aist-inputs"><div className="source-basis">Reference: AIST Technical Report 13</div>
 <label className="checkbox-field"><input type="checkbox" checked={d.runwayOnly} onChange={e=>onChange({runwayOnly:e.target.checked})}/>Roof, wind, seismic and other building actions do not load this girder</label>
 <p className="form-note">AIST combinations are projected to the runway girder. The reference building requires its own load and frame design.</p>
 <label className="field"><span>Crane load concurrency</span><select aria-label="Crane load concurrency" value={d.concurrency??'tr13'} onChange={e=>onChange({concurrency:e.target.value as Inputs['concurrency']})}><option value="tr13">TR-13 / DG7: impact without side thrust, one crane with impact</option><option value="full">Also fully concurrent (ASCE 7 crane loads as live load L)</option></select></label>
 <div className="field-grid"><label className="field"><span>AIST building class</span><select aria-label="AIST building class" value={d.buildingClass} onChange={e=>onChange({buildingClass:e.target.value as Inputs['buildingClass']})}><option value="A">A · over 500,000</option><option value="B">B · 100,000–500,000</option><option value="C">C · 20,000–100,000</option><option value="D">D · under 20,000</option></select></label>{field('Building load repetitions','buildingCycles','ratio')}</div>
 <label className="checkbox-field"><input type="checkbox" checked={d.classConfirmed} onChange={e=>onChange({classConfirmed:e.target.checked})}/>Building class specified by owner</label>
 <p className="form-note">Building class A–D is separate from CMAA crane duty class and the number of fatigue stress fluctuations.</p>
 <details className="advanced-inputs"><summary>Girder bearing & actual restraints</summary><div className="field-grid">{field('Actual rail depth','railDepth')}{field('Support bearing length','bearingLength')}{field('Minimum net flange area','netFlangeArea','area','Actual least net area across both flanges, including hole deductions and stagger under AISC B4.3. Enter bf × tf only after confirming no flange holes. Zero means unverified.')}{field('Bottom-flange brace spacing','bottomBraceSpacing')}{field('Axial effective length','axialLength')}{field('Torsional effective length','torsionalLength')}{field('Runway occupancy live load','liveLoad','lineLoad')}</div><p className="form-note">Effective lengths and brace spacing describe the real girder. Values are not taken from representative 3D supports. Top-flange restraint spacing is in Geometry.</p></details>
 <details className="advanced-inputs"><summary>Rail fastening & support requirements</summary><div className="field-grid"><label className="field"><span>Exposure</span><select value={d.environment} onChange={e=>onChange({environment:e.target.value as Inputs['environment']})}><option value="interior">Interior · {format(6.35,'length',units,4)} minimum</option><option value="exterior">Exterior · {format(7.9375,'length',units,4)} minimum</option></select></label><label className="field"><span>Support load path</span><select value={d.supportType} onChange={e=>onChange({supportType:e.target.value as Inputs['supportType']})}><option value="bracket">Column bracket · under {format(50*4448.221615,'force',units)}</option><option value="column">Direct column bearing</option></select></label>{field('Opposing rail clip spacing','clipSpacing')}<label className="field"><span>Rail fasteners</span><select value={d.fastener} onChange={e=>onChange({fastener:e.target.value as Inputs['fastener']})}><option value="clips">Opposing clip / clamp pairs</option><option value="hook">Hook bolts</option></select></label></div><label className="checkbox-field"><input type="checkbox" checked={d.railPad} onChange={e=>onChange({railPad:e.target.checked})}/>Elastomeric rail pad · {format(609.6,'length',units)} clip maximum</label><p className="form-note">Clip strength, welds, thermal movement and bracket/column capacity require their actual engineering details.</p></details>
 </div>;
}
export function AistFatigueInputs({input,onChange}:{input?:Inputs;onChange:(patch:Partial<Inputs>)=>void}){const d=input??emptyAistInputs;return <><label className="field"><span>Fatigue material point</span><select value={d.fatiguePoint} onChange={e=>onChange({fatiguePoint:e.target.value as Inputs['fatiguePoint']})}>{['top-left','top-right','bottom-left','bottom-right'].map(v=><option key={v} value={v}>{v.replace('-',' flange · ')} edge</option>)}</select></label>{/* TR-13 / DG7 base fatigue on one crane; several cranes together only when operations make that a repeated state. */}<label className="field"><span>Fatigue crane arrangement</span><select value={d.fatigueCranes??'all'} onChange={e=>onChange({fatigueCranes:e.target.value as Inputs['fatigueCranes']})}><option value="all">Every arrangement of the cranes present (conservative)</option><option value="single">One crane at a time (TR-13 / DG7)</option></select></label><Text label="AISC A-3.1 detail item / drawing" value={d.fatigueReference} onChange={fatigueReference=>onChange({fatigueReference})}/><Text label="Owner stress-fluctuation basis" value={d.cycleSource} onChange={cycleSource=>onChange({cycleSource})}/><p className="form-note">Cds + Cvs + 0.5Css; no impact or strength factors. Cycles must include wheel passages, loaded/empty returns and variable-amplitude damage. The selected detail category must match the actual drawing and fabrication.</p></>;}
export function CraneAistInputs({crane,index,onChange,numeric}:{crane:Crane;index:number;onChange:(patch:Partial<CraneDesign>)=>void;numeric:NumericField}){
 const d=crane.design??emptyCraneDesign,field=(label:string,key:keyof CraneDesign,q:Quantity='force')=>numeric(`Crane ${index+1} ${label}`,(d[key]??0) as number,v=>onChange({[key]:v}),q);
 return <details className="advanced-inputs"><summary>AIST crane type & minimum loads</summary>
 <div className="field-grid"><label className="field"><span>Control type</span><select aria-label={`Crane ${index+1} control type`} value={d.control} onChange={e=>onChange({control:e.target.value as CraneDesign['control']})}><option value="cab">Cab / radio / autonomous</option><option value="pendant">Pendant</option></select></label><label className="field"><span>Crane type · Table 3.2</span><select aria-label={`Crane ${index+1} AIST type`} value={d.type} onChange={e=>onChange({type:e.target.value as CraneDesign['type']})}><option value="mill">Mill / ladle / finished magnet</option><option value="magnet">Scrap / slab / clamshell / stripping</option><option value="maintenance">Motor-room maintenance</option><option value="stacker">Stacker</option></select></label>{field('rated lifted load','ratedLoad')}{field('trolley / hoist weight','trolleyWeight')}{field('bridge weight','bridgeWeight')}{d.type==='stacker'&&field('rigid arm weight','rigidArmWeight')}{field('maximum driving-wheel load sum','drivenWheelLoad')}{field('side-thrust share on this runway','sideShare','ratio')}</div>
 <Text label={`Crane ${index+1} lateral distribution source`} value={d.distributionSource} onChange={distributionSource=>onChange({distributionSource})}/>
 <label className="checkbox-field"><input type="checkbox" checked={d.splitConfirmed} onChange={e=>onChange({splitConfirmed:e.target.checked})}/>Loaded and unloaded wheel schedules use the same trolley position</label>
 <p className="form-note">Unloaded wheels provide crane dead weight; the static loaded-minus-unloaded difference provides lifted load. Minimum side thrust is allocated using the entered structural/manufacturer distribution.</p>
 {field('manufacturer full-speed bumper force','bumperForce')}
 <label className="checkbox-field"><input type="checkbox" checked={d.bumperBypassesGirder} onChange={e=>onChange({bumperBypassesGirder:e.target.checked})}/>Stop load follows a designed path that bypasses this girder</label>
 <label className="checkbox-field"><input type="checkbox" checked={d.guideRollers} onChange={e=>onChange({guideRollers:e.target.checked})}/>Guide rollers · manufacturer-specific analysis required</label>
 </details>;
}
