import type {ReactNode} from 'react';
import type {RunwayDetails} from '../engine/runwayDetails';
import {angleTie,defaultSingleAngle,defaultDoubleAngle} from '../engine/angleTie';
import {aiscAngles} from '../data/aiscAngles';
import {format,formatSectionMass,type Quantity} from '../engine/units';
export default function AngleTieInputs({value,onChange,numeric,units}:{value:RunwayDetails;onChange:(d:RunwayDetails)=>void;units:'US'|'SI';numeric:(label:string,v:number,change:(v:number)=>void,q?:Quantity)=>ReactNode}){
 const a=angleTie(value),key=a.paired?'doubleAngle':'singleAngle',input={...(a.paired?defaultDoubleAngle:defaultSingleAngle),...value.brace[key],connectionStyle:a.connectionStyle};
 const edit=(patch:Partial<typeof input>)=>onChange({...value,brace:{...value.brace,[key]:{...input,...patch}}});
 const top=a.connectionStyle==='top-flange-angle',activeShape=top?a.topFlange.shape:input.shape;
 const editTop=(patch:Partial<typeof a.topFlange>)=>edit({topFlange:{...a.topFlange,...patch}});
 return <details className="form-details" open><summary>{a.paired?'Double-angle':'Single-angle'} tie geometry</summary>
  <label className="field"><span>Angle connection detail</span><select aria-label="Angle connection detail" value={a.connectionStyle} onChange={e=>edit({connectionStyle:e.target.value as typeof a.connectionStyle})}><option value="top-flange-angle">Slotted top-flange angle · supplied figure</option><option value="gusseted">Gusseted angles at both flanges</option></select></label>
  <label className="field"><span>AISC tie angle</span><select aria-label="AISC tie angle" value={activeShape} onChange={e=>top?editTop({shape:e.target.value}):edit({shape:e.target.value})}>{!a.shape&&<option value={activeShape} disabled>Select a valid L-section</option>}{aiscAngles.map(s=><option key={s.name} value={s.name}>{s.name} · {formatSectionMass(s.weight,units)} each</option>)}</select></label>
  <dl className="bracket-section-properties">{([['Vertical leg',a.depth],['Outstanding leg',a.leg],['Thickness',a.thickness]] as const).map(([label,v])=><div key={label}><dt>{label}</dt><dd>{format(v,'length',units,4)}</dd></div>)}<div><dt>Angles per tie</dt><dd>{a.paired?2:1}</dd></div></dl>
  {top?<><div className="field-grid">{([['Tie offset toward girder end','endSetback'],['Angle / tie plate width','width'],['Tie plate thickness','plateThickness'],['Top flange / cap overlap','lap'],['Bolt diameter','boltDiameter'],['Bolt pitch along runway','boltPitch'],['Horizontal slot length','slotLength'],['Column shim pack','shimThickness'],['Plate washer thickness','washerThickness'],['Top flange lap weld · reference','weldSize']] as const).map(([label,k])=><div key={k}>{numeric(label,a.topFlange[k],v=>editTop({[k]:v}))}</div>)}</div><p className="input-purpose"><b>Load path:</b> top flange/cap → tie plate → bolted angle → shimmed column flange. {a.paired?'Two clip angles straddle one tie plate.':'One clip angle supports the tie plate.'} No diaphragm or lower-flange tie is shown.</p><p className="input-purpose"><b>Slots:</b> along runway X; nominal centered travel ±{format(Math.max(0,(a.topFlange.slotLength-a.topFlange.boltDiameter)/2),'length',units,3)}. Fit-up geometry only; bolt installation and movement design must establish usable travel.</p><details className="input-guidance"><summary>Figure interpretation & design scope</summary><p className="form-note">Inspired by supplied Figure 14. Standard holes in the column and lap; real horizontal slots in the vertical angle legs and shims, with plate washers. The top tie plate is welded to the girder top flange or cap. Column stiffeners, if required by local checks, remain part of the column design. No slot capacity, lower-flange restraint or fatigue approval is inferred from the sketch.</p></details></>:<><div className="field-grid">{([['Angle end setback across runway','setback'],['Tie offset toward girder end','endSetback'],['Angle saddle length along runway','saddleLength'],['Angle attachment lap','lap'],['Angle gusset thickness','gussetThickness'],['Angle lap weld leg · reference','weldSize']] as const).map(([label,k])=><div key={k}>{numeric(label,input[k],v=>edit({[k]:v}))}</div>)}</div>
  <p className="input-purpose"><b>Fit check:</b> lap length, end clearance, adjacent ties and receiving flange. <b>Design pending:</b> angle/gusset/weld strength, fatigue and movement.</p>
  <details className="input-guidance"><summary>Orientation & modeling assumptions</summary><p className="form-note">The vertical leg connects to the gussets; the outstanding leg points away. Length follows the girder-to-column gap. Top and bottom ties are shown separately. Weld sizes are preview inputs. Column root welds remain unsized pending design.</p></details>
  </>}
 </details>;
}
