import {isExistingBracketType,existingBracketProfile} from '../engine/bracketProfiles';
import ConnectionOptions from './ConnectionOptions';
import {bracketArrangement,tieArrangement} from '../engine/connectionOptions';
import {defaultBracket} from '../engine/bracketInputs';
import type { ReactNode } from 'react';
import {defaultSimpleSupport} from '../engine/simpleSupports';
import type { RunwayDetails } from '../engine/runwayDetails';
import type { Quantity } from '../engine/units';
const labels:Record<string,string>={endGap:'Clear gap between girders',guideTravel:'Sliding travel, each direction',temperatureRise:'Temperature rise from erection',temperatureFall:'Temperature fall from erection',settingTolerance:'End setting tolerance',Fy:'Yield strength, Fy',Fu:'Tensile strength, Fu',Fexx:'Weld electrode, Fexx',rows:'Bolt rows (two columns)',diameter:'Bolt diameter',gauge:'Bolt gauge',pitch:'Bolt pitch',edge:'Edge distance',thickness:'Plate thickness',projection:'Load-to-weld eccentricity',weldSize:'Fillet leg',weldLength:'Effective weld length',grade:'Bolt grade',surface:'Faying surface class',width:'Width',length:'Length',reach:'Lateral reach',gussetThickness:'Central gusset thickness',connectionLength:'Unbraced gusset length',stiffenerWidth:'Stiffener outstand',stiffenerThickness:'Stiffener thickness',cope:'Web-side corner cope',headWidth:'Rail head width',headThickness:'Rail head thickness',baseWidth:'Rail base width',baseThickness:'Rail base thickness',webThickness:'Rail web thickness',padAllowable:'Pad allowable compression',padSource:'Pad rating source',clipWidth:'Keeper length along rail',clipThickness:'Keeper plate thickness',clipProjection:'Keeper cantilever projection',clipWeld:'Keeper root fillet',jointGap:'Rail expansion gap',jointPlateThickness:'Each joint-bar thickness',jointPlateHeight:'Joint-bar height',jointBoltDiameter:'Joint bolt diameter',jointPitch:'Joint bolt pitch',jointEdge:'Joint bolt edge distance',temperatureRange:'Rail temperature swing',twistLimit:'Rail twist limit (rad)',railLateralLimit:'Rail lateral limit, L / n',railGauge:'Nominal rail gauge',alignmentTolerance:'Rail setting allowance',levelTolerance:'Rail level tolerance',rotationClearance:'Girder end rotation gap',temperatureMaximum:'Maximum steel temperature',corrosionProtected:'Corrosion protection provided',x:'Station',point:'Flange edge',category:'Fatigue category',reference:'Detail reference',cycles:'Stress fluctuations',liftFraction:'Fraction of rated lift',name:'Name',id:'Detail ID',steel:'Steel specification',bolting:'Bolting requirements',welding:'Welding requirements',inspection:'Inspection',erection:'Erection sequence',railAlignment:'Rail alignment'};
Object.assign(labels,{longitudinalSetback:'Tie setback from bearing center',saddleLength:'Saddle length along runway',saddleThickness:'Flange saddle thickness',webGap:'Saddle clearance from web',clearance:'Clearance below cap / saddle',enabled:'Include column bracket',reach:'Column face to runway centerline',seatLength:'Seat length along runway',seatProjection:'Seat / rib projection from column',seatThickness:'Seat plate thickness',ribDepth:'Rib depth',ribThickness:'Each rib thickness',ribSpacing:'Rib center-to-center spacing',rootWeld:'Rib-to-column fillet',seatWeld:'Seat-to-rib fillet',deflectionLimit:'Bracket deflection limit',rotationLimit:'Bracket rotation limit (rad)',depth:'Column depth at bracket',width:'Width',flangeThickness:'Column flange thickness',webThickness:'Web thickness',confirmed:'Receiving geometry and material confirmed',unbracedLength:'Largest column flange unbraced length',axialDemand:'Concurrent column axial force from other loads',source:'Receiver geometry / material source',loadPathConfirmed:'Separate horizontal ties and locating / sliding attachments confirmed'});
const ratio=new Set(['rotationLimit','rows','temperatureRise','temperatureFall','temperatureRange','twistLimit','railLateralLimit','temperatureMaximum','cycles','liftFraction']);
const options:Record<string,string[]>={grade:['A325','A490'],surface:['A','B'],point:['top-left','top-right','bottom-left','bottom-right'],category:['A','B','B1','C','D','E','E1']};
export default function RunwayDetailInputs({value,onChange,numeric,system,units='US'}:{units?:'US'|'SI';system:'simple'|'continuous';value:RunwayDetails;onChange:(v:RunwayDetails)=>void;numeric:(label:string,value:number,onChange:(v:number)=>void,q?:Quantity)=>ReactNode}){
 const edit=(path:(string|number)[],v:unknown)=>{const copy=structuredClone({...value,bracket:value.bracket??structuredClone(defaultBracket),simpleSupport:value.simpleSupport??defaultSimpleSupport});let target:any=copy;for(const k of path.slice(0,-1))target=target[k];target[path.at(-1)!]=v;onChange(copy);};
 const fields=(v:Record<string,unknown>,path:(string|number)[],prefix=''):ReactNode=><div className="detail-input-grid">{Object.entries(v).filter(([key])=>!['arrangement','referenceDetail','singleAngle','doubleAngle','tipDepth','corbelShape','existing','wideFlange'].includes(key)&&!(path[0]==='bracket'&&bracketArrangement(value.bracket)==='rolled-corbel'&&['ribDepth','ribThickness','ribSpacing'].includes(key))).filter(([key])=>!(path[0]==='bracket'&&path.length===1&&isExistingBracketType(bracketArrangement(value.bracket))&&['ribDepth','ribThickness','ribSpacing','rootWeld','seatWeld','rotationLimit'].includes(key))).map(([key,x])=>{const at=[...path,key],label=key==='enabled'&&path.includes('flangeAttachment')?'Direct flange saddle attachment':key==='reach'&&path.includes('brace')?'Lateral reach':path[0]==='bracket'&&bracketArrangement(value.bracket)==='rolled-corbel'&&key==='rootWeld'?'Corbel-to-column fillet':path[0]==='bracket'&&bracketArrangement(value.bracket)==='rolled-corbel'&&key==='seatWeld'?'Seat-to-corbel fillet':labels[key]??key,full=prefix?`${prefix} · ${label}`:label;
  if(typeof x==='number')return <div className="detail-value" key={key}>{numeric(full,x,n=>edit(at,n),key==='temperatureMaximum'?'temperature':['temperatureRise','temperatureFall','temperatureRange'].includes(key)?'temperatureChange':key==='axialDemand'?'force':['Fy','Fu','Fexx','padAllowable'].includes(key)?'stress':ratio.has(key)?'ratio':'length')}</div>;
  if(typeof x==='boolean')return <label key={key} className="checkbox-field"><input type="checkbox" checked={x} onChange={e=>edit(at,e.target.checked)}/>{label}</label>;
  if(typeof x==='string')return <label key={key} className={options[key]?'field':'field detail-wide'}><span>{label}</span>{options[key]?<select aria-label={full} value={x} onChange={e=>edit(at,e.target.value)}>{options[key].map(o=><option key={o}>{o}</option>)}</select>:<textarea aria-label={full} rows={x.length>100?3:1} value={x} onChange={e=>edit(at,e.target.value)}/>}</label>;
  if(Array.isArray(x))return <div className="detail-wide" key={key}>{x.map((row,i)=><details key={i} className="form-details"><summary>{row.name??`${key} ${i+1}`}</summary>{fields(row,[...at,i],`${key} ${i+1}`)}<button className="text-button" disabled={x.length===1} onClick={()=>edit(at,x.filter((_,j)=>j!==i))}>Remove</button></details>)}<button className="text-button" disabled={x.length>=(key==='spectrum'?8:16)} onClick={()=>edit(at,[...x,{...x.at(-1),...(key==='fatigueDetails'?{id:`F${x.length+1}`,name:'New fatigue detail'}:{name:'New duty bin'})}])}>Add {key==='spectrum'?'duty bin':'fatigue detail'}</button></div>;
  return <details key={key} className="form-details detail-wide"><summary>{key==='flangeAttachment'?'Direct flange attachment':key==='connection'?'Double-cover connection':key==='receiver'?'Receiving column':key}</summary>{fields(x as Record<string,unknown>,at,prefix)}</details>;
 })}</div>;
 return <><ConnectionOptions value={value} onChange={onChange} numeric={numeric} system={system} units={units}/><p className="input-purpose"><b>Connection inputs:</b> define the actual force-transfer path. Reference framing does not establish building capacity.</p>{Object.entries({...value,bracket:value.bracket??structuredClone(defaultBracket),simpleSupport:value.simpleSupport??defaultSimpleSupport}).filter(([key])=>key!=='endStop'&&key!=='endBearing'&&key!=='reviewed'&&(key!=='end'||!value.endBearing?.enabled||system!=='simple')&&(key!=='simpleSupport'||system==='simple')&&(key!=='brace'||tieArrangement(value)==='paired-bars')).map(([key,v])=><details key={key} className="form-details"><summary>{{bracket:isExistingBracketType(bracketArrangement(value.bracket))?'New seat / receiving column dimensions':'Column bracket dimensions',simpleSupport:'Independent girder ends / shared supports',material:'Plate & weld materials',brace:'Both-flange ties',end:'End / longitudinal connection',bearing:'Bearing & stiffeners',rail:'Rail, keepers & joints',criteria:'Owner criteria',fatigueDetails:'Fatigue detail register',spectrum:'Duty spectrum',fabrication:'Fabrication & inspection notes'}[key]}</summary>{key==='bracket'&&bracketArrangement(value.bracket)==='twin-rib'&&<p className="form-note">Two rectangular plate ribs welded directly to the column flange, with a continuous seat plate. Gravity bearings only; lateral and longitudinal forces use separate column attachments. Enter surveyed receiver properties. Local column checks do not establish frame or foundation adequacy.</p>}{key==='simpleSupport'&&<p className="form-note">Each bay bears independently. Left end locates longitudinally; right end slides. Ties attach separately to the column. S-04 shows the shared bracket, gap and movement allowances. Column-side flexible attachments require project design; enable the welded bracket checks below for the seat and ribs. Temperature changes are measured from erection.</p>}{Array.isArray(v)?fields({[key]:v},[]):fields(v as Record<string,unknown>,[key],key==='brace'?'Tie':key==='end'?'End':key==='bearing'?'Bearing':'')}</details>)}</>;
}
