import type { CalculationSnapshot } from '../engine/types';
import {format} from '../engine/units';
import {usesExistingBracket} from '../engine/existingBracket';
import {activeEndBearing,slidingPhrase} from '../engine/endBearingInputs';
import {detailRef,detailTitles} from './sheetGraphics';

// Drawing notes use project data without assigning unverified building capacities; references to details
// resolve to detail / sheet when the set is assembled.
export function structuralGeneralNotes(s:CalculationSnapshot){
 const d=s.input.details,weldedBracket=detailRef(detailTitles.weldedBracket);
 return [
  'VERIFY ALL DIMENSIONS, ELEVATIONS AND EXISTING CONDITIONS BEFORE FABRICATION. DO NOT SCALE DRAWINGS. REPORT DISCREPANCIES TO THE ENGINEER.',
  d?d.fabrication.steel:'PROVIDE STRUCTURAL STEEL OF THE GRADES SPECIFIED IN THE CALCULATION REPORT. VERIFY MATERIAL GRADES BEFORE FABRICATION.',
  'PROVIDE BOLTS, HOLES AND FAYING SURFACES AS DETAILED. PRETENSION GIRDER CONNECTION BOLTS. INSTALL RAIL-JOINT BOLTS SNUG-TIGHT IN LONGITUDINAL SLOTS.',
  d?`PROVIDE ${format(d.material.Fexx,'stress',s.input.units)} WELD METAL. USE QUALIFIED WELDING PROCEDURES AND PERSONNEL. PROVIDE CONTINUOUS FILLETS WHERE NOTED. SMOOTH STARTS / STOPS. ${s.input.existingColumn?.enabled&&s.input.existingColumn.isNew?'SHOP WELD BRACKETS AND TIE GUSSETS TO THE NEW COLUMNS; NO WELDING TO EXISTING STEEL.':'FIELD WELD ATTACHMENTS TO EXISTING STEEL AS FLAGGED; VERIFY WELDABILITY AND PREPARE SURFACES.'}`:'PROVIDE WELDS AS SPECIFIED IN THE APPROVED CONNECTION DETAILS. USE QUALIFIED WELDING PROCEDURES AND PERSONNEL. FIELD WELD ATTACHMENTS TO EXISTING STEEL AS FLAGGED.',
  s.input.system==='simple'&&d?`PROVIDE INDEPENDENT BEARINGS AND TIES AT EACH GIRDER END. LEFT END LOCATES; RIGHT END SLIDES.${activeEndBearing(s.input)?` BOLT BEARINGS WITH STANDARD HOLES AT THE LOCATING END AND SLOTS, PLATE WASHERS AND ${slidingPhrase(activeEndBearing(s.input)!)} AT THE SLIDING END (${detailRef(detailTitles.endBearing)}).`:''} KEEP GIRDER AND CAP ENDS CLEAR; SEE ${detailRef(detailTitles.supportEnd(s.input.spans.length>1))}. PROVIDE TEMPORARY RESTRAINT UNTIL PERMANENT TIES ARE COMPLETE.`:'FIT BEARING STIFFENERS TO FLANGES. KEEP BEARING SEATS LEVEL. PROVIDE TEMPORARY RESTRAINT UNTIL BOTH-FLANGE TIES AND PERMANENT CONNECTIONS ARE COMPLETE.',
  'INSPECT WELDS, BOLT INSTALLATION AND FAYING SURFACES. PERFORM THE INSPECTION AND NDT REQUIRED BY THE PROJECT SPECIFICATIONS AND CALCULATION REPORT.',
  'VERIFY RAIL GAUGE, ALIGNMENT, LEVEL AND OPERATING CLEARANCES WITH THE CRANE SUPPLIER. COMPLETE INSPECTION AND COMMISSIONING BEFORE CRANE OPERATION.',
  usesExistingBracket(s.input)?`EXISTING BRACKETS, CONTINUITY PLATES AND BUILDING ARE DASHED. NEW BOLTED SPREADERS ARE SOLID; SEE ${detailRef(detailTitles.existingBracket)}. VERIFY SURVEY AND EXISTING SUPPORT ASSESSMENT. SEAT BOLTS ARE NOT GIRDER HOLD-DOWNS. OPPOSITE RUNWAY IS REFERENCE.`:d?.bracket?.enabled?(s.input.existingColumn?.enabled&&s.input.existingColumn.isNew?`NEW COLUMNS, WELDED BRACKETS${s.input.columnBase?.enabled?`, BASE PLATES AND FOOTINGS (${weldedBracket}, ${detailRef(detailTitles.newColumn)})`:` (${weldedBracket})`} ARE NEW WORK, DRAWN SOLID. THE EXISTING BUILDING IS NOT SHOWN. OPPOSITE RUNWAY SHOWN FOR CONTEXT.`:`DASHED BUILDING FRAMING, ANCHORS AND FOUNDATIONS ARE REFERENCE ONLY. SOLID WELDED BRACKETS: SEE ${weldedBracket}. VERIFY EXISTING SECTIONS AND ATTACHMENTS. OPPOSITE RUNWAY SHOWN FOR CONTEXT.`):'DASHED BUILDING FRAMING, BRACKETS, ANCHORS AND FOUNDATIONS ARE REFERENCE ONLY. VERIFY EXISTING SECTIONS AND ATTACHMENTS. OPPOSITE RUNWAY SHOWN FOR CONTEXT; SEE CALCULATIONS FOR SCOPE.',
 ].map(v=>v.toUpperCase());
}
