"""Actual municipal crane permits versus the unchanged demonstration inputs."""
import json
from pathlib import Path
from xml.sax.saxutils import escape
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor

ROOT=Path(__file__).resolve().parents[1]
trials=json.loads((ROOT/'output/permit-sizing/sizing-results.json').read_text())
assert len(trials)==10
EVERETT='https://lfportal.everettwa.gov/WebLink/DocView.aspx?dbid=0&id=2096929&page=1'
RED='https://permits.puyallupwa.gov/Portal/Permit/GetFile?docId=107692'
INK=HexColor('#173448'); PALE=HexColor('#edf3f6'); RULE=HexColor('#c8d4dc'); WARN=HexColor('#fff1da')
styles=getSampleStyleSheet()
for name,font,size,leading in [('TitleX','Helvetica-Bold',25,29),('H','Helvetica-Bold',16,21),('B','Helvetica',9,13),('S','Helvetica',8,11),('L','Helvetica-Bold',10,14),('C','Helvetica',8,11),('CH','Helvetica-Bold',8,11)]:
 styles.add(ParagraphStyle(name,fontName=font,fontSize=size,leading=leading,textColor=INK,spaceAfter=7))
def p(t,style='B',raw=False):return Paragraph(t if raw else escape(str(t)),styles[style])
def table(rows,widths,highlight=()):
 t=Table([[p(v,'CH' if i==0 else 'C') for v in row] for i,row in enumerate(rows)],colWidths=widths,repeatRows=1)
 t.setStyle(TableStyle([('VALIGN',(0,0),(-1,-1),'TOP'),('BACKGROUND',(0,0),(-1,0),PALE),('LINEBELOW',(0,0),(-1,-1),.5,RULE),('LEFTPADDING',(0,0),(-1,-1),7),('RIGHTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]+[('BACKGROUND',(0,i),(-1,i),WARN) for i in highlight]))
 return t
def link(url,label):return f'<link href="{escape(url)}" color="#126783">{escape(label)}</link>'
def footer(c,d):
 c.saveState();c.setFillColor(INK);c.setFont('Helvetica-Bold',8);c.drawString(48,758,'CRANECALC / ACTUAL PERMIT SIZING REVIEW');c.setFont('Helvetica',8);c.drawRightString(564,758,'08 OCT 2026');c.setStrokeColor(RULE);c.line(48,747,564,747);c.line(48,43,564,43);c.drawString(48,29,'Sizing reasonableness and model audit / demonstration remains unchanged');c.drawRightString(564,29,str(d.page));c.restoreState()
def check(t,key):return next(c for c in t['checks'] if c['id']==key)
def snap(t):return json.loads((ROOT/'output/permit-sizing'/f'{t["id"]}.json').read_text())
def keeper_bound(t):return max(c['utilization'] for c in snap(t)['checks'] if c['id'].startswith('detail-full-cycle-RC'))
base=next(t for t in trials if t['shape']=='W24X250')
story=[p('Is the sample beam reasonable?','TitleX'),p('The W24X250 is heavy relative to the actual permit assemblies.','H'),p('It passes the app\'s current fictitious case, but it is a conservative demonstration selection rather than an established economical size. Basic vertical bending and deflection do not drive its weight. Twist and the app\'s welded rail-keeper fatigue treatment are the key issues to resolve before reducing it.'),p('Actual permitted assemblies','L'),table([
 ['Project / permit','Runway span or support arrangement','Selected runway assembly','Nominal beam + cap weight'],
 ['Boeing / Everett\nB2306-034','25\'-6" column spacing; pinned runway ends','W24X76 + C15X33.9','109.9 lb/ft'],
 ['Red Dot / Puyallup\nPRCTI20230447','Existing 29\'-0" column bay; 22\'-0" model segment between knee regions','W18X76 + C15X33.9','109.9 lb/ft'],
 ['Red Dot / same permit','44\'-6" column bay; 41\'-6" principal model segment','W30X99 + C15X33.9','132.9 lb/ft'],
 ['Current app demonstration','Three independent 25\'-0" bays','Bare W24X250','250.0 lb/ft'],
 ],[119,155,131,111],(4,)),Spacer(1,9),p('The sample is 2.27 times the nominal beam-plus-cap weight of the Everett assembly and 1.88 times that of the Red Dot W30 assembly. These weights exclude rail, connections and stiffeners. Greater weight does not directly imply equivalent lateral or torsional performance.'),p('What this evidence supports','L'),p('Two actual municipal permit packages supply three runway arrangements. They establish that substantially lighter capped assemblies are used in real crane projects. They do not prove those assemblies satisfy this sample\'s loads, welded-keeper details or owner criteria, and they are not a twelve-permit validation set.'),p(link(EVERETT,'Everett municipal permit scan')+' - report printed pp. 7, 19-20, 24; viewer pp. 26, 38-39, 43. '+link(RED,'Puyallup accepted permit PDF')+' - PDF pp. 1, 8, 14, 26-28, 53-54.','S',True),PageBreak()]

story += [p('Compare loads and support details','H'),p('Everett: similar bay length and wheel-load magnitude','L'),p('Smithwick report SE-DS-RPT-17691, revision 1, dated July 25, 2023, covers a 120-ft bridge with seven 1/4-ton trolleys. The crane weighs 48,200 lb; each trolley weighs 1,700 lb. Hoist capacity alone would be a misleading comparison.'),table([
 ['Quantity','Everett permit','Current demonstration'],
 ['Wheel spacing / wheels per runway truck','16\'-0" / 2','10\'-0" / 2'],
 ['Static vertical wheel load','16.92 dead + 1.44 lifted = 18.36 kip','8.00 dead + 12.00 lifted = 20.00 kip'],
 ['Vertical impact','25%; 4.59 kip per wheel','25%; 5.00 kip per wheel'],
 ['Side thrust','3.08 kip in source wheel-load table','2.00 kip entered per wheel'],
 ['Runway fatigue cycles','500,000; AIST building Class B','1,000,000 supplied wheel stress cycles; AIST building Class C'],
 ['Rail / top-flange treatment','60-lb/yd rail; channel-capped beam','Fictitious 6-in plate rail; welded keeper pairs'],
 ],[165,176,175]),Spacer(1,9),p('For a simple-span, wheel-only vertical comparison, the maximum moment is 117.045 kip-ft for the Everett loading and 160.000 kip-ft for the sample. The sample is about 37% higher. For Everett, one wheel at midspan governs because the 16-ft wheel spacing is wide relative to the bay. These are independent screening calculations, not a reproduction of the complete frame model.'),p('Red Dot: the same 10-ton rating, different runway system','L'),p('The accepted AHBL package includes original crane drawings showing a 40-ft runway gauge, an existing capped W18 runway and a capped W30 extension. Knee-braced supports shorten the effective beam segments. The RISA moving-load schedule uses a single 24.8-kip point and a 1.1 combination multiplier; it must not be treated as two 24.8-kip wheels. The manufacturer\'s complete wheel schedule was not established from the reviewed pages.'),p('A source inconsistency remains: the Red Dot RISA W30 section lists Ix = 5,269.516 in4 and Iy = 346.179 in4, while the separate composite-section worksheet lists 5,537.70 and 443.002 in4. The drawing establishes the assembly size; an exact analytical replay would first need this discrepancy resolved.','S'),p('Both examples use cap channels. The app\'s detailed design model currently supports symmetric bare rolled I-sections; it does not establish full capped-section torsion, fatigue, attachment or frame adequacy.','S'),PageBreak()]

rows=[['Bare W-shape','Vertical bending D/C','Vertical defl. (in)','Twist D/C','Keeper fatigue range D/C','Failed checks']]
for t in trials[:7]:
 rows.append([t['shape'],f'{check(t,"major")["utilization"]:.3f}',f'{check(t,"vertical")["demand"]/25.4:.3f}',f'{check(t,"rail-twist")["utilization"]:.3f}',f'{keeper_bound(t):.3f}',str(len(t['failures']))])
story += [p('What the unchanged app requires','H'),p('Seven section trials use the same 25-ft bays, loads, 25-ft both-flange restraint spacing, 1/4-in rail eccentricity, connections, rail, duty bins and owner criteria. Only section properties and the corresponding gross net-flange input change.'),table(rows,[83,86,85,74,104,84],(7,)),Spacer(1,9),p('D/C above 1.0 fails. Vertical deflection limit = 0.500 in; twist limit = 0.005 rad. Keeper range is the largest local stress range divided by the Category D all-cycle bound for 1,000,000 cycles. It is separate from cumulative fatigue damage. Failed-check counts include repeated keeper locations and are not independent failure modes.','S'),p('W24X250 is the lightest passing section among these seven W24 trials, not an optimized catalogue search. W24X229 passes the twist check but still fails keeper fatigue. The W24X250 major-axis bending ratio is only 0.134 and vertical deflection is 0.072 in.'),p('Separate W24X131 sensitivity runs','L')]
rows=[['Restraint spacing','Rail eccentricity','Twist D/C','Keeper range D/C','Outcome']]
for t in [trials[1],*trials[7:]]:
 rows.append([f'{t["braceFeet"]:g} ft',f'{t["eccIn"]:g} in',f'{check(t,"rail-twist")["utilization"]:.3f}',f'{keeper_bound(t):.3f}','FAIL - fatigue remains'])
story += [table(rows,[102,99,84,115,116]),Spacer(1,9),p('Adding actual both-flange restraint at 12.5-ft spacing reduces W24X131 twist utilization from 3.169 to 0.277. Setting eccentricity to zero alone reduces it only to 2.787. These are hypothetical changed support layouts, not changes made to the app demonstration. Supporting framing for the extra restraints would require its own design.'),p('All ten runs have valid inputs and completed normal calculation checks. Failures remain recorded; no capacity, criterion, formula or export gate was changed.','S'),PageBreak()]

s131=snap(trials[1]);p131=s131['input'];rr=s131['detailResults'];rail=p131['details']['rail'];dd=rr['demands']
local=6*((dd['railLateral']*p131['aist']['railDepth']+dd['railVertical']*abs(p131['railEccentricity']))/rail['baseWidth']*rail['clipProjection']+dd['railLateral']*(rail['baseThickness']+rail['clipThickness']/2))/(rail['clipWidth']*p131['section']['tf']**2)
story += [p('Why the sample became heavy','H'),p('1. The twist criterion and restraint layout','L'),p('The 0.005-rad limit is entered fictitious owner/supplier criteria; it is not demonstrated here as a universal AIST limit. The bare member has free warping at its ends and finite both-flange ties at 25-ft intervals. A cap channel changes the section and load path; a bare W-shape of equal weight is not a substitute.'),p('2. The local keeper-fatigue treatment','L'),p('The app superposes the full factored strength-envelope local keeper stress, with reversal, on every fatigue bin and both flange edges. This uses 3.20-kip lateral and 36.80-kip vertical strength-envelope forces even though the separate fatigue force envelope is 1.00 kip lateral and 20.00 kip vertical. It also checks the largest resulting range against all 1,000,000 cycles without threshold credit.'),p(f'For W24X131, that added local stress alone is +/-{local/6.894757293:.3f} ksi, or {2*local/6.894757293:.3f} ksi of range, before global bending/warping is added. The Category D all-cycle allowable range is approximately 13.015 ksi. This implementation is explicitly conservative and can dominate a size selection; these permit packages do not validate that particular superposition rule.'),p('3. The sample duty and hardware','L'),p('The million-cycle spectrum, 6-in fabricated rail, welded keeper geometry and selected fatigue categories are fictitious. They should be replaced by a documented crane duty, rail system, force-sharing model and detail category before presenting a size as representative of a practical project.'),p('Recommended action','L'),p('Retain W24X250 as the passing conservative demonstration while revising the realistic sample around an actual manufacturer wheel schedule and a validated runway/rail attachment system. Prioritize capped-section analysis, keeper force transfer and fatigue stress ranges, then evaluate genuine restraint alternatives and search lighter sections. Do not reduce the beam merely to resemble a permit drawing.'),p('Independent check and reproduction','L'),p('For the sample\'s two 20-kip wheels, symmetric about midspan: delta = P*a*(3L^2 - 4a^2)/(24*E*Ix), with a = 90 in, L = 300 in and E = 29,000 ksi. Independently substituted values reproduce all ten app vertical deflections within 0.000001 in. For the wheel-only moment screen, the maximum of the one-wheel and admissible two-wheel positions was used.'),p('Re-run: npx tsx scripts/reviewPermitSizing.ts. Results and full snapshots: output/permit-sizing/. Independent numerical checks: independent-verification.json and wheel-moment-verification.json. This report: scripts/renderPermitSizing.py. The live demonstration and its existing PDF have not been resized.','S')]
out=ROOT/'output/pdf/crane-runway-actual-permit-sizing-review.pdf'
SimpleDocTemplate(str(out),pagesize=(612,792),leftMargin=48,rightMargin=48,topMargin=62,bottomMargin=58,title='CraneCalc - actual crane permit beam sizing review',author='CraneCalc review').build(story,onFirstPage=footer,onLaterPages=footer)
print(out)
